// GERADO por scripts/generar-mapa-imagenes.mjs — nao editar a mao.
// Rode 'npm run contenido' para regenerar.
//
// O Metro so resolve require com caminho estatico, por isso o mapa e literal.
const IMAGENES = {
  'major-00': require('../../assets/madremaria/tarot/major-00.jpg'),
  'major-01': require('../../assets/madremaria/tarot/major-01.jpg'),
  'major-02': require('../../assets/madremaria/tarot/major-02.jpg'),
  'major-03': require('../../assets/madremaria/tarot/major-03.jpg'),
  'major-04': require('../../assets/madremaria/tarot/major-04.jpg'),
  'major-05': require('../../assets/madremaria/tarot/major-05.jpg'),
  'major-06': require('../../assets/madremaria/tarot/major-06.jpg'),
  'major-07': require('../../assets/madremaria/tarot/major-07.jpg'),
  'major-08': require('../../assets/madremaria/tarot/major-08.jpg'),
  'major-09': require('../../assets/madremaria/tarot/major-09.jpg'),
  'major-10': require('../../assets/madremaria/tarot/major-10.jpg'),
  'major-11': require('../../assets/madremaria/tarot/major-11.jpg'),
  'major-12': require('../../assets/madremaria/tarot/major-12.jpg'),
  'major-13': require('../../assets/madremaria/tarot/major-13.jpg'),
  'major-14': require('../../assets/madremaria/tarot/major-14.jpg'),
  'major-15': require('../../assets/madremaria/tarot/major-15.jpg'),
  'major-16': require('../../assets/madremaria/tarot/major-16.jpg'),
  'major-17': require('../../assets/madremaria/tarot/major-17.jpg'),
  'major-18': require('../../assets/madremaria/tarot/major-18.jpg'),
  'major-19': require('../../assets/madremaria/tarot/major-19.jpg'),
  'major-20': require('../../assets/madremaria/tarot/major-20.jpg'),
  'major-21': require('../../assets/madremaria/tarot/major-21.jpg'),
  'paus-01': require('../../assets/madremaria/tarot/paus-01.jpg'),
  'paus-02': require('../../assets/madremaria/tarot/paus-02.jpg'),
  'paus-03': require('../../assets/madremaria/tarot/paus-03.jpg'),
  'paus-04': require('../../assets/madremaria/tarot/paus-04.jpg'),
  'paus-05': require('../../assets/madremaria/tarot/paus-05.jpg'),
  'paus-06': require('../../assets/madremaria/tarot/paus-06.jpg'),
  'paus-07': require('../../assets/madremaria/tarot/paus-07.jpg'),
  'paus-08': require('../../assets/madremaria/tarot/paus-08.jpg'),
  'paus-09': require('../../assets/madremaria/tarot/paus-09.jpg'),
  'paus-10': require('../../assets/madremaria/tarot/paus-10.jpg'),
  'paus-11': require('../../assets/madremaria/tarot/paus-11.jpg'),
  'paus-12': require('../../assets/madremaria/tarot/paus-12.jpg'),
  'paus-13': require('../../assets/madremaria/tarot/paus-13.jpg'),
  'paus-14': require('../../assets/madremaria/tarot/paus-14.jpg'),
  'copas-01': require('../../assets/madremaria/tarot/copas-01.jpg'),
  'copas-02': require('../../assets/madremaria/tarot/copas-02.jpg'),
  'copas-03': require('../../assets/madremaria/tarot/copas-03.jpg'),
  'copas-04': require('../../assets/madremaria/tarot/copas-04.jpg'),
  'copas-05': require('../../assets/madremaria/tarot/copas-05.jpg'),
  'copas-06': require('../../assets/madremaria/tarot/copas-06.jpg'),
  'copas-07': require('../../assets/madremaria/tarot/copas-07.jpg'),
  'copas-08': require('../../assets/madremaria/tarot/copas-08.jpg'),
  'copas-09': require('../../assets/madremaria/tarot/copas-09.jpg'),
  'copas-10': require('../../assets/madremaria/tarot/copas-10.jpg'),
  'copas-11': require('../../assets/madremaria/tarot/copas-11.jpg'),
  'copas-12': require('../../assets/madremaria/tarot/copas-12.jpg'),
  'copas-13': require('../../assets/madremaria/tarot/copas-13.jpg'),
  'copas-14': require('../../assets/madremaria/tarot/copas-14.jpg'),
  'espadas-01': require('../../assets/madremaria/tarot/espadas-01.jpg'),
  'espadas-02': require('../../assets/madremaria/tarot/espadas-02.jpg'),
  'espadas-03': require('../../assets/madremaria/tarot/espadas-03.jpg'),
  'espadas-04': require('../../assets/madremaria/tarot/espadas-04.jpg'),
  'espadas-05': require('../../assets/madremaria/tarot/espadas-05.jpg'),
  'espadas-06': require('../../assets/madremaria/tarot/espadas-06.jpg'),
  'espadas-07': require('../../assets/madremaria/tarot/espadas-07.jpg'),
  'espadas-08': require('../../assets/madremaria/tarot/espadas-08.jpg'),
  'espadas-09': require('../../assets/madremaria/tarot/espadas-09.jpg'),
  'espadas-10': require('../../assets/madremaria/tarot/espadas-10.jpg'),
  'espadas-11': require('../../assets/madremaria/tarot/espadas-11.jpg'),
  'espadas-12': require('../../assets/madremaria/tarot/espadas-12.jpg'),
  'espadas-13': require('../../assets/madremaria/tarot/espadas-13.jpg'),
  'espadas-14': require('../../assets/madremaria/tarot/espadas-14.jpg'),
  'ouros-01': require('../../assets/madremaria/tarot/ouros-01.jpg'),
  'ouros-02': require('../../assets/madremaria/tarot/ouros-02.jpg'),
  'ouros-03': require('../../assets/madremaria/tarot/ouros-03.jpg'),
  'ouros-04': require('../../assets/madremaria/tarot/ouros-04.jpg'),
  'ouros-05': require('../../assets/madremaria/tarot/ouros-05.jpg'),
  'ouros-06': require('../../assets/madremaria/tarot/ouros-06.jpg'),
  'ouros-07': require('../../assets/madremaria/tarot/ouros-07.jpg'),
  'ouros-08': require('../../assets/madremaria/tarot/ouros-08.jpg'),
  'ouros-09': require('../../assets/madremaria/tarot/ouros-09.jpg'),
  'ouros-10': require('../../assets/madremaria/tarot/ouros-10.jpg'),
  'ouros-11': require('../../assets/madremaria/tarot/ouros-11.jpg'),
  'ouros-12': require('../../assets/madremaria/tarot/ouros-12.jpg'),
  'ouros-13': require('../../assets/madremaria/tarot/ouros-13.jpg'),
  'ouros-14': require('../../assets/madremaria/tarot/ouros-14.jpg'),
};

export function imagenDeCarta(id) {
  return IMAGENES[id] ?? null;
}

export default IMAGENES;
