// datos/frases.js — O BANCO DA FRASE DO DIA (lib/fraseDoDia.js).
// Duas fornadas da fabrica de 01/09, deduplicadas e re-filtradas.
export const FRASES = Object.freeze([
  'Recomeçar não apaga a história. Só devolve a caneta pra sua mão.',
  'O sol nasce sem pedir licença ao dia anterior. Faça igual.',
  'O primeiro passo de qualquer recomeço é curto, desajeitado e dado hoje.',
  'Página virada não é página arrancada. O livro continua nas suas mãos.',
  'Ninguém recomeça de onde caiu. Recomeça de onde decide ficar de pé.',
  'Quem passa o dia olhando o telefone esquece que a própria vida também chama.',
  'Estar de corpo e atenção no mesmo lugar: poucas coisas impressionam tanto e custam tão pouco.',
  'O hoje pede pouco: sua atenção enquanto acontece.',
  'Saudade mora no passado. Faça visitas curtas e volte pra casa, que é aqui.',
  'A conversa mais importante da manhã acontece na frente do espelho, antes de qualquer bom-dia.',
  'Trate-se com o cuidado que você espera receber. As pessoas aprendem olhando.',
  'Cuidar de você não é egoísmo. É manutenção de quem sustenta a própria casa.',
  'Seu valor não diminui quando alguém deixa de olhar. Ouro continua ouro no escuro.',
  'Amor-próprio não é frase de espelho. É a hora de dormir, o prato de comida, a companhia que você escolhe.',
  'Diga um não necessário hoje. Amor-próprio também se treina em palavras curtas.',
  'Pressa colhe fruta verde. O tempo do pomar existe por um motivo.',
  'Paciência não é braço cruzado. É continuar plantando sem desenterrar a semente pra conferir.',
  'O que é sólido leva tempo. Tijolo por tijolo também é um jeito de amar.',
  'Um ano não se vive de uma vez. Ainda bem: hoje só cobra um dia.',
  'Não confunda silêncio com fim. Tem coisa que amadurece longe dos olhos.',
  'Coragem, hoje, pode ser levantar da cama e arrumar o lençol. Conta igual.',
  'Você não precisa dar conta da semana toda. Só dos próximos dez minutos.',
  'Fazer com medo também é fazer. O medo cansa de seguir quem não para.',
  'Coragem grande é coragem pequena praticada em dia comum.',
  'Levante, lave o rosto, resolva uma pendência pequena. Coragem também tem tamanho de bolso.',
  'Um dia só não muda tudo. Mas nenhuma mudança começa sem um dia igual a este.',
  'Hoje parece pouco? Talvez. Também é tudo o que existe de concreto agora.',
  'Dias bem vividos se somam em silêncio. Um dia a conta aparece.',
  'Não subestime um dia comum. É onde a vida acontece quase sempre.',
  'O dia de hoje não se repete. Gaste com quem está presente — a começar por você.',
  'Saudade é visita: receba, sirva um café, escute. Depois acompanhe até a porta.',
  'Quem você é às nove da manhã diz mais que qualquer promessa de meia-noite.',
  'Cresça na direção da luz, como toda planta que se preza. Menos discurso, mais direção.',
  'Sentir falta não é fraqueza. Morar dentro da falta é que sai caro.',
  'Arrume um canto da casa hoje. Ordem do lado de fora manda recado pro lado de dentro.',
  'Escolha bem as palavras que você repete pra você. Palavra repetida vira companhia do dia todo.',
  'Comparação rouba o valor do seu passo. Compare o seu hoje com o seu ontem, e mais nada.',
  'Não se trata de esquecer essa pessoa. Trata-se de lembrar que você também existe.',
  'O cuidado que você aceita dos outros aprende com o cuidado que você se dá.',
  'Um caminho longo se cumpre de um único jeito: um hoje de cada vez.',
  'Chorar lava. Com o olho limpo, o caminho aparece com mais nitidez.',
  'Dez minutos de silêncio por dia. As respostas importantes costumam falar baixo.',
  'Você não controla o coração de ninguém. Controla o próprio dia — e isso já é muito.',
  'A distância também ensina. Tem coisa que só se enxerga de longe.',
  'Faça hoje algo que ontem você adiou. Pequeno serve. Feito vale mais que perfeito.',
  'Quem rega a própria vida todos os dias floresce sem precisar anunciar.',
  'A pressa que quer resolver tudo hoje é a mesma que estraga o que pede tempo.',
  'Paciência não é espera parada. É trabalho diário no que depende de você.',
  'Um dia ruim não cancela o caminho. Amanhece de novo, e você segue no jogo.',
  'Presença se percebe. Quem está por perto nota quando você começa a habitar a própria vida.',
  'Apresente-se pra você com o respeito de quem apresenta alguém importante.',
  'O espelho não pede elogio nem desculpa. Pede honestidade com um pouco de carinho.',
  'Reconstruir demora menos quando você para de demolir com o próprio pensamento.',
  'Escolha uma tarefa e faça com capricho. Capricho é amor em forma de detalhe.',
  'O passado é bom professor e péssimo endereço. Estude por lá, more por aqui.',
  'Força não é ausência de sentimento. É sentir tudo e ainda fazer o café, a cama e o dia.',
  'Gente que se respeita comunica sem falar. Esse tipo de mudança dispensa legenda.',
  'Devagar e todo dia chega mais longe que depressa de vez em quando.',
  'Antes de querer espaço no pensamento de alguém, ocupe o seu próprio dia com coisa boa.',
  'O fio que importa agora liga você à sua própria vida. Segure firme.',
  'Recomeçar não apaga o que passou. Só decide o que você faz com o agora.',
  'Não existe dia oficial pra recomeçar. Uma terça-feira comum serve.',
  'Recomeço de verdade é discreto: ninguém percebe, mas você sabe.',
  'Voltar atrás numa decisão errada não é fraqueza. É pontaria.',
  'O que ficou pra trás pesa menos quando você para de carregar no colo.',
  'Recomeçar pequeno é recomeçar. O tamanho do primeiro passo não define a caminhada.',
  'Errar ontem te deu informação. Usar essa informação hoje é o recomeço.',
  'Você não precisa resolver tudo pra começar de novo. Precisa começar por uma coisa.',
  'Todo recomeço tem uma parte sem graça. Atravessar essa parte é o trabalho.',
  'Desistir de um caminho não é desistir de você.',
  'O dia não cobra explicação sobre ontem. Ele só abre a porta e espera.',
  'Recomeçar cansa menos do que fingir que está tudo bem.',
  'Estar de corpo e atenção no mesmo lugar é raro. Por isso se nota tanto.',
  'O momento presente não pede aplauso. Pede só que você repare nele.',
  'Quem escuta de verdade não prepara a resposta enquanto a outra pessoa fala.',
  'Presença é o que sobra quando você para de ensaiar o que dizer depois.',
  'O café esfria enquanto você resolve na cabeça um problema que ainda nem existe.',
  'Seu corpo já chegou. Falta convidar a atenção pra acompanhar.',
  'A conversa mais importante do dia costuma ser a que você quase não escuta.',
  'Preocupação é imaginação apontada pro lugar errado. Traga ela de volta pra mesa.',
  'Você não perde o momento por falta de tempo. Perde por excesso de abas abertas na cabeça.',
  'Olhar nos olhos por três segundos a mais muda uma conversa inteira.',
  'O agora é curto. Cabe pouca coisa nele — escolha bem o que entra.',
  'Ninguém nota presença na hora. Nota a falta dela depois.',
  'Paciência não é ficar de braços cruzados. É continuar fazendo sem cobrar colheita todo dia.',
  'As coisas levam o tempo que levam. Sua pressa não entra nessa conta.',
  'O que amadurece à força quebra cedo.',
  'Um passo por dia parece pouco até você olhar pra trás no fim do mês.',
  'Pressa resolve pouco e estraga muito.',
  'O silêncio depois de uma pergunta difícil também é resposta em construção.',
  'Esperar faz parte do caminho. Não é o intervalo dele.',
  'Você rega hoje o que só aparece daqui a meses. Regue mesmo assim.',
  'A pressa quer tudo agora. O que dura pede outra medida de tempo.',
  'Confiar no caminho é fácil de falar. Difícil é não mexer na panela a cada minuto.',
  'Repetir o básico sem plateia: é assim que as coisas sólidas se constroem.',
  'Coragem, na maioria dos dias, é dizer a frase que você vem engolindo.',
  'Mandar a mensagem difícil leva um minuto. Adiar essa mensagem ocupa a semana.',
  'Pedir ajuda não diminui você. Fingir que não precisa é o que sai caro.',
  'Dizer "não sei" em voz alta é coragem que cabe em dois segundos.',
  'O medo não pede licença pra entrar. Mas quem dirige continua sendo você.',
  'Coragem pequena: fazer a ligação que você empurra desde segunda.',
  'Dizer não sem pedir desculpas três vezes também é coragem.',
  'A conversa que você evita já está acontecendo — só que sem você.',
  'Começar mal é melhor que assistir de fora. Perfeição é desculpa elegante.',
  'Admitir que mudou de ideia exige mais coragem do que sustentar teimosia.',
  'O primeiro passo raramente é bonito. Ninguém filma essa parte mesmo.',
  'Coragem grande é feita de coragens pequenas empilhadas em dias comuns.',
  'Um dia bem vivido não precisa ser um dia grande.',
  'Hoje é o único pedaço da vida que está de fato nas suas mãos.',
  'Não subestime 24 horas. Muita coisa muda de lugar em bem menos que isso.',
  'O dia de hoje não guarda lugar. O que ficou de fora, ficou.',
  'Dias comuns carregam a vida inteira. Os especiais são só a moldura.',
  'Se hoje render uma única coisa feita com cuidado, já valeu o dia.',
  'Um dia ruim é um dia ruim. Não é uma vida ruim.',
  'Amanhã se resolve amanhã. Hoje só pede o que cabe em hoje.',
  'Você não vive o caminho de uma vez. Vive um dia, e depois outro.',
  'O dia tem valor mesmo quando ninguém vê o que você fez nele.',
  'Guardar dez minutos do dia pra algo que é só seu muda o peso das outras horas.',
  'O extraordinário costuma nascer disfarçado de dia comum.',
]);
