const PACKS = Object.freeze({
  pt: Object.freeze({
    title: 'Memória Cósmica',
    profileRow: 'O que Órbi lembra sobre mim',
    intro: 'Quando você ativa, Órbi pode reencontrar informações úteis que você escreveu e conectá-las a uma conversa futura.',
    consentTitle: 'Permitir continuidade entre conversas',
    consentBody: 'A memória começa vazia e pode guardar até 300 trechos de novas mensagens, com até 1.600 caracteres cada, depois da sua autorização.',
    enabled: 'Memória ativada',
    disabled: 'Memória desativada',
    privacy: 'Seu Diário, dados natais, conversas da Comunidade e contexto de casal não entram aqui. Uma lembrança nunca é publicada e nunca prova que sua situação continua igual.',
    rememberedTitle: 'Lembranças visíveis',
    emptyEnabled: 'Órbi ainda não guardou nenhuma frase. As próximas conversas podem criar lembranças quando houver conteúdo útil.',
    emptyDisabled: 'Ative quando quiser que Órbi conecte conversas futuras ao que você realmente contou.',
    loginTitle: 'Entre para usar uma memória privada',
    loginBody: 'A Memória Cósmica pertence à sua conta e não fica presa a um único aparelho.',
    loginCta: 'Entrar ou criar conta',
    removeLabel: 'Apagar esta lembrança',
    removeTitle: 'Apagar lembrança?',
    removeBody: 'Órbi não poderá mais usar esta frase para dar continuidade às conversas.',
    removeConfirm: 'Apagar',
    clearAll: 'Apagar todas as lembranças',
    clearTitle: 'Apagar toda a Memória Cósmica?',
    clearBody: 'Isso remove todas as frases guardadas. A autorização permanece ativa até você desligá-la.',
    clearConfirm: 'Apagar tudo',
    cancel: 'Cancelar',
    retry: 'Tentar novamente',
    loadError: 'Não foi possível carregar sua memória agora.',
    saveError: 'Não foi possível salvar essa preferência.',
    deleteError: 'Não foi possível apagar a lembrança.',
    loading: 'Carregando sua memória…',
    source: 'Você escreveu ao Órbi',
    topics: Object.freeze({ love: 'Amor', decision: 'Decisão', self: 'Autoconhecimento', work: 'Trabalho', curiosity: 'Curiosidade', general: 'Conversa' }),
  }),
  es: Object.freeze({
    title: 'Memoria Cósmica',
    profileRow: 'Lo que Órbi recuerda de mí',
    intro: 'Cuando la activas, Órbi puede recuperar información útil que escribiste y conectarla con una conversación futura.',
    consentTitle: 'Permitir continuidad entre conversaciones',
    consentBody: 'La memoria comienza vacía y puede guardar hasta 300 fragmentos de mensajes nuevos, de hasta 1.600 caracteres cada uno, después de tu autorización.',
    enabled: 'Memoria activada',
    disabled: 'Memoria desactivada',
    privacy: 'Tu Diario, datos natales, conversaciones de la Comunidad y contexto de pareja no entran aquí. Un recuerdo nunca se publica ni demuestra que tu situación sigue igual.',
    rememberedTitle: 'Recuerdos visibles',
    emptyEnabled: 'Órbi todavía no guardó ninguna frase. Las próximas conversaciones pueden crear recuerdos cuando haya contenido útil.',
    emptyDisabled: 'Actívala cuando quieras que Órbi conecte conversaciones futuras con lo que realmente contaste.',
    loginTitle: 'Inicia sesión para usar una memoria privada',
    loginBody: 'La Memoria Cósmica pertenece a tu cuenta y no queda atada a un solo dispositivo.',
    loginCta: 'Entrar o crear una cuenta',
    removeLabel: 'Borrar este recuerdo',
    removeTitle: '¿Borrar el recuerdo?',
    removeBody: 'Órbi ya no podrá usar esta frase para dar continuidad a las conversaciones.',
    removeConfirm: 'Borrar',
    clearAll: 'Borrar todos los recuerdos',
    clearTitle: '¿Borrar toda la Memoria Cósmica?',
    clearBody: 'Esto elimina todas las frases guardadas. La autorización permanece activa hasta que la desactives.',
    clearConfirm: 'Borrar todo',
    cancel: 'Cancelar',
    retry: 'Intentar de nuevo',
    loadError: 'No se pudo cargar tu memoria ahora.',
    saveError: 'No se pudo guardar esta preferencia.',
    deleteError: 'No se pudo borrar el recuerdo.',
    loading: 'Cargando tu memoria…',
    source: 'Lo escribiste a Órbi',
    topics: Object.freeze({ love: 'Amor', decision: 'Decisión', self: 'Autoconocimiento', work: 'Trabajo', curiosity: 'Curiosidad', general: 'Conversación' }),
  }),
  en: Object.freeze({
    title: 'Cosmic Memory',
    profileRow: 'What Órbi remembers about me',
    intro: 'When enabled, Órbi can retrieve useful information you wrote and connect it to a future conversation.',
    consentTitle: 'Allow continuity between conversations',
    consentBody: 'Memory starts empty and may keep up to 300 excerpts from new messages, up to 1,600 characters each, after you give permission.',
    enabled: 'Memory enabled',
    disabled: 'Memory disabled',
    privacy: 'Your Diary, birth data, Community conversations, and couple context do not enter this memory. A memory is never published and never proves that your situation is still the same.',
    rememberedTitle: 'Visible memories',
    emptyEnabled: 'Órbi has not saved any sentence yet. Future conversations can create memories when there is useful content.',
    emptyDisabled: 'Enable it when you want Órbi to connect future conversations to what you actually shared.',
    loginTitle: 'Sign in to use private memory',
    loginBody: 'Cosmic Memory belongs to your account and is not tied to a single device.',
    loginCta: 'Sign in or create account',
    removeLabel: 'Delete this memory',
    removeTitle: 'Delete memory?',
    removeBody: 'Órbi will no longer be able to use this sentence to continue future conversations.',
    removeConfirm: 'Delete',
    clearAll: 'Delete all memories',
    clearTitle: 'Delete all Cosmic Memory?',
    clearBody: 'This removes every saved sentence. Permission remains enabled until you turn it off.',
    clearConfirm: 'Delete all',
    cancel: 'Cancel',
    retry: 'Try again',
    loadError: 'Your memory could not be loaded right now.',
    saveError: 'This preference could not be saved.',
    deleteError: 'The memory could not be deleted.',
    loading: 'Loading your memory…',
    source: 'You wrote this to Órbi',
    topics: Object.freeze({ love: 'Love', decision: 'Decision', self: 'Self-understanding', work: 'Work', curiosity: 'Curiosity', general: 'Conversation' }),
  }),
});

const DATE_FORMATTERS = Object.freeze({
  pt: new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }),
  es: new Intl.DateTimeFormat('es-ES', { day: '2-digit', month: 'short', year: 'numeric' }),
  en: new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
});

export function cosmicMemoryCopy(lang) {
  return PACKS[lang] || PACKS.pt;
}

export function cosmicMemoryDate(value, lang = 'pt') {
  const date = new Date(value);
  if (!Number.isFinite(date.getTime())) return '';
  return (DATE_FORMATTERS[lang] || DATE_FORMATTERS.pt).format(date);
}

export const COSMIC_MEMORY_LANGUAGES = Object.freeze(Object.keys(PACKS));
