export const PACK = {
  title: 'Cosmic Mirror',
  subtitle: 'A portrait made only from the readings you actually experienced.',
  eyebrow: 'Your history, not a guess',
  periods: { 7: '7 days', 30: '30 days', all: 'Available history' },
  emptyTitle: 'Your mirror starts with your first spread',
  emptyBody: 'Once your Diary has cards, this space will show real repetitions without reading your question or inventing a pattern.',
  emptyCta: 'Draw my cards',
  firstTitle: 'Your first signal is already saved',
  firstBody: ({ card }) => `${card} opened this period. It is too early to call it a pattern; the next encounter will make the comparison more useful.`,
  developingTitle: 'Your history is gaining contrast',
  developingBody: ({ readings, unique }) =>
    `${readings} spreads already hold ${unique} different cards, but no repetition leads without a tie. The mirror waits for more encounters before calling anything a pattern.`,
  patternBody: ({ card, count, suit, theme }) => [
    `${card} returned most often (${count}×).`,
    suit ? `${suit} held the most encounters.` : null,
    theme ? `${theme} was your most chosen theme.` : null,
  ].filter(Boolean).join(' '),
  metrics: {
    readings: 'spreads',
    unique: 'different cards',
    reversed: 'reversed',
    suit: 'dominant card group',
    theme: 'most present theme',
  },
  noDominant: 'No dominant pattern',
  trendUp: ({ count }) => `${count} more ${count === 1 ? 'spread' : 'spreads'} than the previous period`,
  trendDown: ({ count }) => `${count} fewer ${count === 1 ? 'spread' : 'spreads'} than the previous period`,
  trendSame: 'The same number of spreads as the previous period',
  receiptTitle: 'How this mirror was built',
  receiptBody: ({ readings, cards, period }) =>
    `${readings} ${readings === 1 ? 'spread' : 'spreads'}, ${cards} ${cards === 1 ? 'card' : 'cards'}, period: ${period}. The calculation stays on this device and does not use private questions or reflections. It uses what remains in the Diary: up to 200 non-favorite readings, plus favorites; older readings already removed are not included.`,
  share: 'Share my mirror',
  shareEyebrow: 'My Cosmic Mirror',
  shareFooter: 'Made from my real history · cosmicguide.cloud',
  suits: { paus: 'Wands', copas: 'Cups', espadas: 'Swords', ouros: 'Pentacles', maiores: 'Major Arcana' },
  themes: { Amor: 'Love', Carreira: 'Career', Dinheiro: 'Money', Energia: 'Energy', 'Saúde': 'Well-being' },
};
