export const PACK = {
  title: 'Espejo Cósmico',
  subtitle: 'Un retrato hecho únicamente con las lecturas que viviste.',
  eyebrow: 'Tu historial, no una suposición',
  periods: { 7: '7 días', 30: '30 días', all: 'Historial disponible' },
  emptyTitle: 'Tu espejo empieza con la primera tirada',
  emptyBody: 'Cuando haya cartas en el Diario, este espacio mostrará repeticiones reales sin leer tu pregunta ni inventar un patrón.',
  emptyCta: 'Sacar mis cartas',
  firstTitle: 'La primera señal ya está guardada',
  firstBody: ({ card }) => `${card} abrió este período. Aún es pronto para llamarlo patrón; el próximo encuentro hará más útil la comparación.`,
  developingTitle: 'Tu historial está ganando contraste',
  developingBody: ({ readings, unique }) =>
    `${readings} tiradas ya reúnen ${unique} cartas diferentes, pero ninguna repetición lidera sin empate. El espejo espera más encuentros antes de llamarlo patrón.`,
  patternBody: ({ card, count, suit, theme }) => [
    `${card} fue la carta que más volvió (${count}×).`,
    suit ? `${suit} concentró más encuentros.` : null,
    theme ? `${theme} fue el tema más elegido.` : null,
  ].filter(Boolean).join(' '),
  metrics: {
    readings: 'tiradas',
    unique: 'cartas diferentes',
    reversed: 'invertidas',
    suit: 'grupo de cartas dominante',
    theme: 'tema más presente',
  },
  noDominant: 'Sin dominante',
  trendUp: ({ count }) => `${count} ${count === 1 ? 'tirada' : 'tiradas'} más que en el período anterior`,
  trendDown: ({ count }) => `${count} ${count === 1 ? 'tirada' : 'tiradas'} menos que en el período anterior`,
  trendSame: 'El mismo número de tiradas que en el período anterior',
  receiptTitle: 'Cómo se armó este espejo',
  receiptBody: ({ readings, cards, period }) =>
    `${readings} ${readings === 1 ? 'tirada' : 'tiradas'}, ${cards} ${cards === 1 ? 'carta' : 'cartas'}, período: ${period}. El cálculo ocurre en este dispositivo y no usa preguntas ni reflexiones privadas. Considera lo que aún está en el Diario: hasta 200 lecturas no favoritas, además de las favoritas; las lecturas antiguas ya eliminadas no entran.`,
  share: 'Compartir mi espejo',
  shareEyebrow: 'Mi Espejo Cósmico',
  shareFooter: 'Hecho con mi historial real · cosmicguide.cloud',
  suits: { paus: 'Bastos', copas: 'Copas', espadas: 'Espadas', ouros: 'Oros', maiores: 'Arcanos Mayores' },
  themes: { Amor: 'Amor', Carreira: 'Carrera', Dinheiro: 'Dinero', Energia: 'Energía', 'Saúde': 'Bienestar' },
};
