const pack = Object.freeze({
  brand: 'COSMIC GUIDE',
  edition: 'CELESTIAL NOTE',
  alignmentEyebrow: 'ALIGN YOUR SKY',
  shareTitle: 'Your encounter, as a card',
  shareBody: 'A visual keepsake of the result revealed now.',
  shareButton: 'Share card',
  shareA11yHint: 'Creates a PNG and opens the sharing options.',
  preparing: 'Preparing the PNG…',
  shared: 'Card opened for sharing.',
  downloaded: 'Card saved as a PNG.',
  unavailable: 'The card could not be created now. Try again.',
  privacyNote: 'Only the encounter appears — no birth data, city, or personal text.',
  dialogTitle: 'Share Cosmic Guide encounter',
  fileName: 'cosmic-guide-align-your-sky',
  footer: 'COSMIC GUIDE · A CALCULATED ENCOUNTER',
  aspectDetail: ({ transit, aspect, natal }) => `${transit} · ${aspect} · ${natal}`,
  aspectMeta: ({ phase, orb }) => `${phase} · ${orb}° orb`,
  nextEventDetail: ({ date }) => `Next sky event · ${date}`,
  nextEventMeta: 'Ephemeris calculated for the current sky',
  shareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Align your sky`,
  mirrorEdition: 'COSMIC MIRROR',
  mirrorEyebrow: 'MY REAL PATTERN',
  mirrorTitle: 'Your mirror, as a card',
  mirrorBody: 'A visual portrait made only from cards recorded in your Diary.',
  mirrorButton: 'Share Mirror card',
  mirrorPrivacyNote: 'The card uses card patterns only—never your private question or reflection.',
  mirrorDialogTitle: 'Share Cosmic Mirror',
  mirrorFileName: 'cosmic-guide-cosmic-mirror',
  mirrorFooter: 'COSMIC GUIDE · AVAILABLE HISTORY',
  mirrorMeta: ({ readings, period }) => `${readings} ${readings === 1 ? 'spread' : 'spreads'} · ${period}`,
  mirrorShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Cosmic Mirror`,
  tarotEdition: 'PERSONAL SPREAD',
  tarotEyebrow: 'MY CARDS',
  tarotTitle: 'Your spread, as a card',
  tarotBody: 'A visual record of the cards you just revealed.',
  tarotButton: 'Share spread card',
  tarotPrivacyNote: 'Only theme, spread and cards enter the card—no question, focus, sign or reflection.',
  tarotDialogTitle: 'Share Cosmic Guide spread',
  tarotFileName: 'cosmic-guide-my-spread',
  tarotFooter: 'COSMIC GUIDE · REVEALED CARDS',
  tarotMeta: ({ theme, spread }) => [theme, spread].filter(Boolean).join(' · '),
  tarotShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · My spread`,
});

export default pack;
