const pack = Object.freeze({
  brand: 'COSMIC GUIDE',
  edition: 'NOTA CELESTE',
  alignmentEyebrow: 'ALINEA TU CIELO',
  shareTitle: 'Tu encuentro, en una tarjeta',
  shareBody: 'Un recuerdo visual del resultado revelado ahora.',
  shareButton: 'Compartir tarjeta',
  shareA11yHint: 'Crea un PNG y abre las opciones para compartir.',
  preparing: 'Preparando el PNG…',
  shared: 'Tarjeta abierta para compartir.',
  downloaded: 'Tarjeta guardada en PNG.',
  unavailable: 'No fue posible crear la tarjeta ahora. Inténtalo de nuevo.',
  privacyNote: 'Solo aparece el encuentro — sin nacimiento, ciudad ni textos personales.',
  dialogTitle: 'Compartir encuentro de Cosmic Guide',
  fileName: 'cosmic-guide-alinea-tu-cielo',
  footer: 'COSMIC GUIDE · UN ENCUENTRO CALCULADO',
  aspectDetail: ({ transit, aspect, natal }) => `${transit} · ${aspect} · ${natal}`,
  aspectMeta: ({ phase, orb }) => `${phase} · orbe ${orb}°`,
  nextEventDetail: ({ date }) => `Próximo evento del cielo · ${date}`,
  nextEventMeta: 'Efeméride calculada para el cielo actual',
  shareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Alinea tu cielo`,
  mirrorEdition: 'ESPEJO CÓSMICO',
  mirrorEyebrow: 'MI PATRÓN REAL',
  mirrorTitle: 'Tu espejo, en una tarjeta',
  mirrorBody: 'Un retrato visual hecho solo con las cartas registradas en tu Diario.',
  mirrorButton: 'Compartir tarjeta del Espejo',
  mirrorPrivacyNote: 'La tarjeta usa solo patrones de las cartas: nunca tu pregunta ni tu reflexión privada.',
  mirrorDialogTitle: 'Compartir Espejo Cósmico',
  mirrorFileName: 'cosmic-guide-espejo-cosmico',
  mirrorFooter: 'COSMIC GUIDE · HISTORIAL DISPONIBLE',
  mirrorMeta: ({ readings, period }) => `${readings} ${readings === 1 ? 'tirada' : 'tiradas'} · ${period}`,
  mirrorShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Espejo Cósmico`,
  tarotEdition: 'TIRADA PERSONAL',
  tarotEyebrow: 'MIS CARTAS',
  tarotTitle: 'Tu tirada, en una tarjeta',
  tarotBody: 'Un registro visual de las cartas que acabas de revelar.',
  tarotButton: 'Compartir tarjeta de la tirada',
  tarotPrivacyNote: 'Solo tema, formato y cartas entran en la tarjeta: sin pregunta, foco, signo ni reflexión.',
  tarotDialogTitle: 'Compartir tirada de Cosmic Guide',
  tarotFileName: 'cosmic-guide-mi-tirada',
  tarotFooter: 'COSMIC GUIDE · CARTAS REVELADAS',
  tarotMeta: ({ theme, spread }) => [theme, spread].filter(Boolean).join(' · '),
  tarotShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Mi tirada`,
});

export default pack;
