export const PACK = {
  title: 'Espelho Cósmico',
  subtitle: 'Um retrato feito somente com as leituras que você viveu.',
  eyebrow: 'Seu histórico, não um palpite',
  periods: { 7: '7 dias', 30: '30 dias', all: 'Histórico disponível' },
  emptyTitle: 'Seu espelho começa na primeira tiragem',
  emptyBody: 'Quando houver cartas no Diário, este espaço mostra repetições reais sem ler sua pergunta nem inventar um padrão.',
  emptyCta: 'Tirar minhas cartas',
  firstTitle: 'O primeiro sinal já está guardado',
  firstBody: ({ card }) => `${card} abriu este período. Ainda é cedo para chamar isso de padrão; o próximo encontro deixa a comparação mais útil.`,
  developingTitle: 'Seu histórico está ganhando contraste',
  developingBody: ({ readings, unique }) =>
    `${readings} tiragens já reúnem ${unique} cartas diferentes, mas nenhuma repetição lidera sem empate. O espelho espera mais encontros antes de chamar algo de padrão.`,
  patternBody: ({ card, count, suit, theme }) => [
    `${card} foi a carta que mais voltou (${count}×).`,
    suit ? `${suit} concentrou mais encontros.` : null,
    theme ? `${theme} foi o tema mais escolhido.` : null,
  ].filter(Boolean).join(' '),
  metrics: {
    readings: 'tiragens',
    unique: 'cartas diferentes',
    reversed: 'invertidas',
    suit: 'grupo de cartas dominante',
    theme: 'tema mais presente',
  },
  noDominant: 'Sem dominante',
  trendUp: ({ count }) => `${count} ${count === 1 ? 'tiragem' : 'tiragens'} a mais que no período anterior`,
  trendDown: ({ count }) => `${count} ${count === 1 ? 'tiragem' : 'tiragens'} a menos que no período anterior`,
  trendSame: 'Mesmo número de tiragens do período anterior',
  receiptTitle: 'Como este espelho foi montado',
  receiptBody: ({ readings, cards, period }) =>
    `${readings} ${readings === 1 ? 'tiragem' : 'tiragens'}, ${cards} ${cards === 1 ? 'carta' : 'cartas'}, período: ${period}. O cálculo acontece neste aparelho e não usa pergunta nem reflexão privada. Considera o que ainda está no Diário: até 200 leituras não favoritas, além das favoritas; leituras antigas já removidas não entram.`,
  share: 'Compartilhar meu espelho',
  shareEyebrow: 'Meu Espelho Cósmico',
  shareFooter: 'Feito com meu histórico real · cosmicguide.cloud',
  suits: { paus: 'Paus', copas: 'Copas', espadas: 'Espadas', ouros: 'Ouros', maiores: 'Arcanos Maiores' },
  themes: { Amor: 'Amor', Carreira: 'Carreira', Dinheiro: 'Dinheiro', Energia: 'Energia', 'Saúde': 'Bem-estar' },
};
