const pack = Object.freeze({
  brand: 'COSMIC GUIDE',
  edition: 'NOTA CELESTE',
  alignmentEyebrow: 'ALINHE SEU CÉU',
  shareTitle: 'Seu encontro, em um card',
  shareBody: 'Uma lembrança visual do resultado revelado agora.',
  shareButton: 'Compartilhar card',
  shareA11yHint: 'Cria um PNG e abre as opções de compartilhamento.',
  preparing: 'Preparando o PNG…',
  shared: 'Card aberto para compartilhar.',
  downloaded: 'Card salvo em PNG.',
  unavailable: 'Não foi possível criar o card agora. Tente novamente.',
  privacyNote: 'Só o encontro aparece no card — sem nascimento, cidade ou textos pessoais.',
  dialogTitle: 'Compartilhar encontro do Cosmic Guide',
  fileName: 'cosmic-guide-alinhe-seu-ceu',
  footer: 'COSMIC GUIDE · UM ENCONTRO CALCULADO',
  aspectDetail: ({ transit, aspect, natal }) => `${transit} · ${aspect} · ${natal}`,
  aspectMeta: ({ phase, orb }) => `${phase} · orbe ${orb}°`,
  nextEventDetail: ({ date }) => `Próximo evento do céu · ${date}`,
  nextEventMeta: 'Efeméride calculada para o céu atual',
  shareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Alinhe seu céu`,
  mirrorEdition: 'ESPELHO CÓSMICO',
  mirrorEyebrow: 'MEU PADRÃO REAL',
  mirrorTitle: 'Seu espelho, em um card',
  mirrorBody: 'Um retrato visual feito apenas com as cartas registradas no seu Diário.',
  mirrorButton: 'Compartilhar card do Espelho',
  mirrorPrivacyNote: 'O card usa somente padrões das cartas — nunca sua pergunta ou reflexão privada.',
  mirrorDialogTitle: 'Compartilhar Espelho Cósmico',
  mirrorFileName: 'cosmic-guide-espelho-cosmico',
  mirrorFooter: 'COSMIC GUIDE · HISTÓRICO DISPONÍVEL',
  mirrorMeta: ({ readings, period }) => `${readings} ${readings === 1 ? 'tiragem' : 'tiragens'} · ${period}`,
  mirrorShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Espelho Cósmico`,
  tarotEdition: 'TIRAGEM PESSOAL',
  tarotEyebrow: 'MINHAS CARTAS',
  tarotTitle: 'Sua tiragem, em um card',
  tarotBody: 'Um registro visual das cartas que você acabou de revelar.',
  tarotButton: 'Compartilhar card da tiragem',
  tarotPrivacyNote: 'Só tema, formato e cartas entram no card — sem pergunta, foco, signo ou reflexão.',
  tarotDialogTitle: 'Compartilhar tiragem do Cosmic Guide',
  tarotFileName: 'cosmic-guide-minha-tiragem',
  tarotFooter: 'COSMIC GUIDE · CARTAS REVELADAS',
  tarotMeta: ({ theme, spread }) => [theme, spread].filter(Boolean).join(' · '),
  tarotShareText: ({ title, detail }) => `${title}\n${detail}\n\nCosmic Guide · Minha tiragem`,
});

export default pack;
