export const PACK = {
  title: 'Your Cosmic Album',
  subtitle: '78 cards, real encounters, and patterns only time can reveal.',
  tabs: { album: 'Album', mirror: 'Mirror' },
  progress: ({ seen, total }) => `${seen} of ${total} revealed`,
  progressComplete: 'The whole deck has now passed through your hands.',
  progressMissing: ({ count }) =>
    count === 1 ? 'Only 1 card still holds its mystery.' : `${count} cards still hold their mystery.`,
  draw: 'Start a spread',
  searchPlaceholder: 'Search cards by name',
  filters: {
    all: 'All',
    seen: 'Revealed',
    unseen: 'Hidden',
    favorites: 'Favorites',
    repeated: 'Recurring',
  },
  groups: { maiores: 'Major Arcana', paus: 'Wands', copas: 'Cups', espadas: 'Swords', ouros: 'Pentacles' },
  noResultsTitle: 'No cards here',
  noResultsBody: 'Try another name or filter. Your revealed cards are still stored.',
  hiddenGroupCount: ({ count }) => count === 1 ? '1 hidden card in this group' : `${count} hidden cards in this group`,
  hiddenGroupHint: 'Positions are not shown, so the missing card stays unknown. Start a spread to discover it.',
  favorite: 'Add to favorites',
  unfavorite: 'Remove from favorites',
  encountersTitle: 'Your encounters',
  encountersCount: ({ count }) =>
    count === 1 ? 'Appeared once in your spreads' : `Appeared ${count} times in your spreads`,
  encountersOrientation: ({ upright, reversed }) => `${upright} upright · ${reversed} reversed`,
  firstSeen: ({ date }) => `First recorded encounter on ${date}`,
  lastSeen: ({ date }) => `Most recent encounter on ${date}`,
  legacyHistory: 'This card was already in your album. Detailed history starts with its next encounter.',
  legacyBaseline: 'This card was already in the album before this measurement. The dates and orientations above begin with the first encounter recorded now.',
  studyTitle: 'Study this card',
  studySubtitle: 'Compare both orientations without changing any spread.',
  upright: 'Upright',
  reversed: 'Reversed',
  keywords: 'Keywords',
  scene: 'What to notice in the image',
  meaning: 'Orientation reading',
  advice: 'Question for reflection',
};
