// Lentes breves de los 22 Arcanos Mayores por tema.
// Mantienen el mismo alcance editorial del paquete PT: reflexión situada,
// sin predicción, diagnóstico ni atribuciones tradicionales nuevas.

const pack = {
  'major-00': {
    Amor: 'El pie al borde pregunta si este acercamiento nace de apertura o de impulso. Antes del salto, combina libertad con un límite claro.',
    Carreira: 'El equipaje ligero favorece probar una ruta todavía sin garantías. Ensaya a pequeña escala y mira el terreno antes de dejar lo conocido.',
    Dinheiro: 'El precipicio convierte la espontaneidad en alerta financiera: cabe la curiosidad, no una apuesta sin margen. Define cuánto puedes arriesgar sin afectar lo básico.',
    Energia: 'El caminante muestra ganas de empezar, pero el perro tira de su ropa. Elige una aventura estimulante sin ignorar la señal de cautela.',
    Saúde: 'En esta mirada de autocuidado, el paso pide presencia y un entorno seguro. Prefiere un cambio sencillo de rutina a un salto que supere tus límites.',
  },
  'major-01': {
    Amor: 'El Mago reúne intención y recursos sobre la mesa. En vez de seducir con promesas, muestra con una acción qué vínculo quieres construir.',
    Carreira: 'Las cuatro herramientas ya están disponibles; el reto profesional es elegir una y usarla con foco, no exhibir un potencial disperso.',
    Dinheiro: 'La habilidad se convierte en recurso cuando encuentra ejecución. Haz inventario de lo que sabes producir y prueba una aplicación concreta antes de contar con ingresos.',
    Energia: 'Una mano señala el propósito y la otra, el suelo. Concentra el impulso en una tarea que una idea y gesto, sin activarlo todo a la vez.',
    Saúde: 'En el autocuidado, disponer de muchos recursos no reemplaza la constancia. Elige una práctica accesible, observa tu respuesta y ajusta sin prometerle resultados al cuerpo.',
  },
  'major-02': {
    Amor: 'Entre las dos columnas, la Sacerdotisa protege lo que aún no se dijo. Observa los silencios y pide contexto antes de llenar vacíos con suposiciones.',
    Carreira: 'El rollo medio oculto sugiere información incompleta. Reúne el dato que falta y reserva tu lectura interna antes de anunciar una decisión profesional.',
    Dinheiro: 'No todas las condiciones están visibles en esta negociación. Lee los detalles, espera la información pendiente y distingue intuición de una ventaja todavía no comprobada.',
    Energia: 'La guardiana sentada no desperdicia movimiento. Un intervalo sin estímulos puede mostrar qué demanda merece atención y cuál solo produce ruido.',
    Saúde: 'Esta carta favorece una escucha cuidadosa, no el autodiagnóstico. Registra señales y límites percibidos; ante una preocupación, lleva los hechos a un profesional cualificado.',
  },
  'major-03': {
    Amor: 'En el campo de trigo, el afecto crece con presencia sostenida. Mira si el cuidado circula entre ambos o si alguien se volvió la única fuente del vínculo.',
    Carreira: 'La Emperatriz habla de trabajo que requiere cultivo, no prisa. Protege tiempo para crear y define qué significa madurar esta entrega.',
    Dinheiro: 'La abundancia empieza al hacer rendir lo que ya existe. Nutre un recurso productivo y no confundas generosidad con sostenerlo todo por tu cuenta.',
    Energia: 'El campo fértil pide alternar entre producir y recibir. Recupera energía para algo propio antes de que atender todas las demandas seque tu creatividad.',
    Saúde: 'En la rutina de bienestar, la imagen invita al sustento básico y a la amabilidad contigo. Elige un cuidado posible sin medir el cuerpo por su productividad.',
  },
  'major-04': {
    Amor: 'El trono de piedra pregunta qué límites dan seguridad al vínculo y cuáles se volvieron mando. Nombra una regla que proteja a ambos sin controlar al otro.',
    Carreira: 'El Emperador favorece una responsabilidad visible: alcance, plazo y autoridad necesitan claridad. Estructura el trabajo antes de exigir que se sostenga.',
    Dinheiro: 'La montaña seca y la piedra piden base, no apariencia de control. Ordena obligaciones fijas y margen de decisión antes de asumir un compromiso nuevo.',
    Energia: 'La estructura puede ahorrar fuerza al reducir decisiones repetidas. Crea un marco sencillo para el día, con espacio suficiente para no volverlo rigidez.',
    Saúde: 'En el autocuidado, la disciplina útil es la que cabe en la vida real. Crea un apoyo estable y revisable sin castigar al cuerpo cuando la rutina cambie.',
  },
  'major-05': {
    Amor: 'Ante el maestro y sus discípulos, revisa qué reglas de pareja fueron heredadas. Conserva solo las que aún representan los valores de ambos.',
    Carreira: 'Las llaves a los pies del Hierofante señalan acceso mediante aprendizaje. Busca orientación experimentada, pero comprende el método antes de convertirlo en regla.',
    Dinheiro: 'El consejo especializado puede aclarar una decisión si la autoridad tiene competencia e intereses transparentes. No delegues la elección junto con la duda.',
    Energia: 'Un ritual conocido puede reducir la dispersión. Recupera una práctica que ya dio forma al día, sin obedecer por costumbre a lo que perdió sentido.',
    Saúde: 'Esta mirada valora orientación responsable y una rutina comprensible. Para asuntos clínicos, acude a profesionales habilitados; el símbolo no sustituye una evaluación de salud.',
  },
  'major-06': {
    Amor: 'Bajo el ángel, los Enamorados muestran el instante anterior a elegir. La pregunta central es si deseo, acuerdo y valores apuntan al mismo vínculo.',
    Carreira: 'Dos posibilidades exigen más que comparar ventajas. Elige la ruta que sostiene tus valores profesionales y acepta lo que quedará atrás.',
    Dinheiro: 'Esta decisión financiera expone prioridades enfrentadas. Antes de elegir, di qué valor protege cada opción y qué costo ninguna consigue eliminar.',
    Energia: 'La energía dividida entre dos direcciones pierde fuerza en medio. Nombra el conflicto de valores y ofrece presencia completa a una elección cada vez.',
    Saúde: 'En el bienestar, la coherencia importa más que la regla perfecta. Elige un cuidado compatible con tus límites, el apoyo disponible y la orientación adecuada.',
  },
  'major-07': {
    Amor: 'Las esfinges tiran en sentidos opuestos mientras el conductor sostiene el rumbo. Hablen de una dirección común antes de acelerar la relación.',
    Carreira: 'El Carro concentra fuerzas rivales en una meta. Define un destino profesional medible y coordina los frentes sin confundir velocidad con avance.',
    Dinheiro: 'El impulso sin dirección puede mover mucho y avanzar poco. Asigna un propósito a cada gasto relevante y revisa los que tiran contra tu prioridad.',
    Energia: 'Hay potencia disponible, pero necesita rumbo. Elige un punto de llegada para hoy y conduce las tensiones internas sin intentar aplastarlas.',
    Saúde: 'En el autocuidado, intensidad no significa adecuación. Ajusta el ritmo a tus señales y condiciones, especialmente cuando dos exigencias compitan.',
  },
  'major-08': {
    Amor: 'La mujer toca al león sin violencia. Una conversación firme y amable puede mostrar si la relación recibe límites o solo responde a la presión.',
    Carreira: 'La Fuerza favorece influencia sin confrontación bruta. Sostén tu posición con preparación y paciencia, especialmente ante una reacción defensiva.',
    Dinheiro: 'Aquí el dominio no consiste en apretar hasta romper, sino en contener el impulso sin negarlo. Crea una pausa entre deseo de compra y decisión.',
    Energia: 'La imagen propone regular la potencia, no apagarla. Dirige la intensidad hacia una acción precisa y deja la fuerza bruta fuera de la agenda.',
    Saúde: 'Amabilidad y firmeza pueden convivir en una rutina de cuidado. Respeta molestias y progresión individual sin usar el esfuerzo extremo como prueba de valor.',
  },
  'major-09': {
    Amor: 'La linterna ilumina solo el siguiente paso. Un tiempo de retiro puede aclarar el vínculo, siempre que no se convierta en desaparición sin conversación.',
    Carreira: 'El Ermitaño cambia exposición por investigación. Reserva espacio para profundizar una habilidad y regresa con una pregunta más precisa, no solo con distancia.',
    Dinheiro: 'Antes de seguir el movimiento ajeno, examina tus propios números. La linterna pide una revisión discreta, enfocada en el siguiente compromiso.',
    Energia: 'Reducir el ruido puede devolver dirección al día. Elige un intervalo deliberado y un momento de regreso para que el retiro no se vuelva aislamiento.',
    Saúde: 'La escucha interna puede apoyar el autocuidado, pero no tiene que ser solitaria. Si algo preocupa, organiza lo percibido y pide ayuda específica.',
  },
  'major-10': {
    Amor: 'La rueda invita a reconocer el ciclo del vínculo: cercanía, distancia, reparación o repetición. Busca dónde tu respuesta todavía puede cambiar la vuelta.',
    Carreira: 'Los cambios de contexto alteran tu posición en la rueda. Distingue lo que no controlas de la habilidad que puedes preparar para una próxima apertura.',
    Dinheiro: 'La oscilación pide margen y lectura de ciclo, no apuestas a la suerte. Observa patrones de entrada y salida antes de reaccionar al giro actual.',
    Energia: 'No todos los días ocupan el mismo punto de la rueda. Ajusta la expectativa al momento y conserva una acción pequeña que atraviese la variación.',
    Saúde: 'Las rutinas también pasan por ciclos. Registra cambios, adapta el cuidado con prudencia y busca evaluación profesional ante una señal persistente o preocupante.',
  },
  'major-11': {
    Amor: 'Espada y balanza piden verdad con medida. Separa hechos, interpretación y responsabilidad de cada persona antes de buscar un veredicto sobre el vínculo.',
    Carreira: 'La Justicia favorece criterios explícitos. Documenta entregas, acuerdos y consecuencias para que una decisión profesional no dependa solo de impresiones.',
    Dinheiro: 'Pon valores, plazos y obligaciones en la balanza real. Firma únicamente después de entender la contrapartida y tu parte de la cuenta.',
    Energia: 'El desequilibrio se vuelve más legible al mirar el día sin juicio. Compara demanda y capacidad y retira una obligación que no cabe.',
    Saúde: 'En esta mirada de bienestar, la evidencia vale más que la culpa. Observa datos y contexto; las dudas clínicas requieren evaluación cualificada, no una carta.',
  },
  'major-12': {
    Amor: 'El Colgado cambia la visión al suspender el movimiento. Deja de forzar una respuesta y mira el vínculo desde el lugar que sueles ignorar.',
    Carreira: 'Insistir desde el mismo ángulo aprieta el nudo profesional. Usa la pausa para revisar premisa, costo de espera y aquello que necesita entrega.',
    Dinheiro: 'Una decisión suspendida también tiene costo. Antes de destrabarla, cambia el punto de vista e identifica el sacrificio incluido en cada opción.',
    Energia: 'Hoy, parar puede ser un trabajo legítimo. Suelta una insistencia y observa qué perspectiva aparece cuando la urgencia deja de mandar.',
    Saúde: 'Una pausa no tiene por qué significar abandonar el cuidado. Adapta la exigencia a lo seguro ahora y busca orientación si la limitación persiste.',
  },
  'major-13': {
    Amor: 'La Muerte habla de una forma de vínculo que terminó, no de muerte literal. Reconoce el cierre antes de intentar llamarlo continuidad.',
    Carreira: 'El sol entre las torres aparece después del tránsito. Cierra una función, método o ciclo agotado para liberar atención hacia lo que puede reconstruirse.',
    Dinheiro: 'Quizá un compromiso antiguo ya no sostenga su propósito. Ciérralo con claridad, calcula consecuencias y evita financiar algo solo porque ya comenzó.',
    Energia: 'Sostener un ciclo terminado consume la fuerza de la transición. Elige un gesto concreto de cierre y conserva espacio para el siguiente ritmo.',
    Saúde: 'Aquí la transformación es metáfora de rutina, nunca pronóstico. Deja un hábito inviable con apoyo adecuado y reemplázalo por un cuidado posible.',
  },
  'major-14': {
    Amor: 'El líquido pasa poco a poco entre dos copas. Ajustes pequeños y recíprocos pueden mostrar la medida del encuentro mejor que una gran declaración.',
    Carreira: 'La Templanza combina recursos sin borrar diferencias. Integra dos habilidades por etapas y evalúa la mezcla antes de ampliar el proyecto.',
    Dinheiro: 'La carta favorece proporción: cuánto entra, cuánto sale y cuánto permanece disponible. Corrige un exceso específico en vez de rediseñarlo todo.',
    Energia: 'Un pie en el agua y otro en tierra piden transición gradual. Alterna esfuerzo y recuperación, observando qué dosis mantiene habitable el día.',
    Saúde: 'La moderación orienta aquí una rutina, no una prescripción. Haz cambios graduales dentro de tus límites y lleva necesidades específicas al profesional adecuado.',
  },
  'major-15': {
    Amor: 'Las cadenas permiten salir, pero también ofrecen algo a cambio. Nombra la ganancia oculta que mantiene este patrón afectivo.',
    Carreira: 'El Diablo expone un acuerdo que ata mediante recompensa inmediata. Evalúa qué ventaja sostiene la dependencia y qué límite devolvería capacidad de elegir.',
    Dinheiro: 'Deseo, deuda o estatus puede haberse vuelto cadena. Haz visible el beneficio que alimenta el hábito antes de negociar una salida realista.',
    Energia: 'Un impulso recurrente ocupa más espacio cuando queda sin nombre. Observa disparador, recompensa y costo, y elige una cadena posible de aflojar.',
    Saúde: 'La carta puede reflejar apego a una rutina, no diagnóstico ni culpa. Busca apoyo apropiado ante patrones que parezcan difíciles de cambiar sin ayuda.',
  },
  'major-16': {
    Amor: 'El rayo no crea la grieta: la revela. Di qué estructura del vínculo dejó de sostener verdad, seguridad o respeto.',
    Carreira: 'La corona cae de una torre ya frágil. Protege a las personas y el trabajo esencial; luego reconstruye el proceso desde lo que resistió.',
    Dinheiro: 'Una base financiera inestable pide contención antes que expansión. Identifica la fisura, reduce exposición y no repitas la misma estructura con otro nombre.',
    Energia: 'Después del impacto, la prioridad es un suelo firme. Suspende lo no esencial y concentra presencia en un único frente recuperable.',
    Saúde: 'La Torre no predice una emergencia. Ante una señal aguda o preocupación concreta, busca atención; en lo simbólico, revisa una rutina sin sustento.',
  },
  'major-17': {
    Amor: 'Bajo ocho estrellas, el agua se ofrece al estanque y a la tierra. Un reencuentro pide vulnerabilidad recíproca, no fe usada para ignorar ausencias.',
    Carreira: 'La Estrella aparece después de una ruptura y trabaja con paciencia. Retoma una ambición mediante evidencia pequeña, pública y constante.',
    Dinheiro: 'La esperanza financiera gana suelo cuando se vuelve gesto repetible. Dirige un recurso modesto hacia lo que aún funciona y acompaña sin fantasear rendimientos.',
    Energia: 'Las dos jarras muestran reposición distribuida. Elige una fuente concreta de inspiración y alimenta también la rutina que permite sostenerla.',
    Saúde: 'En esta lectura de autocuidado, el agua sugiere continuidad y atención básica. Valora apoyos pequeños y reales sin atribuir efectos clínicos al símbolo.',
  },
  'major-18': {
    Amor: 'Entre perro y lobo, el camino existe, pero la luz distorsiona los contornos. Evita decidir desde la ansiedad y pide claridad sobre lo ambiguo.',
    Carreira: 'La Luna señala un escenario incompleto, rumores o miedo proyectado. Separa lo confirmado de lo que tu imaginación completó antes de cambiar de rumbo.',
    Dinheiro: 'Las cifras nebulosas no se vuelven seguras por intuición. Aplaza el compromiso, revisa condiciones y pide otra mirada a lo que parece demasiado bueno.',
    Energia: 'El camino nocturno pide un paso menor y menos estímulo. Nombra un miedo verificable y deja el resto sin conclusión hasta que haya luz.',
    Saúde: 'Las sensaciones merecen atención, pero la carta no las explica. Registra el contexto y consulta por síntomas sin convertir el miedo en diagnóstico.',
  },
  'major-19': {
    Amor: 'El niño bajo el sol invita a un afecto visible y sencillo. Di qué aprecias y observa si la alegría puede existir sin actuación.',
    Carreira: 'Los girasoles orientados a la luz favorecen reconocimiento claro. Muestra una entrega concreta y permite que tu valor se entienda sin exceso de adorno.',
    Dinheiro: 'La claridad puede valer más que una oportunidad brillante. Simplifica las cifras, expone costos y elige lo que sigue siendo bueno al verlo completo.',
    Energia: 'El Sol amplifica lo presente. Usa la disposición en una actividad sencilla y compartible sin convertir entusiasmo en una agenda imposible.',
    Saúde: 'El bienestar no necesita convertirse en espectáculo. Observa qué aporta vitalidad de manera sostenible y respeta señales que pidan ajuste o evaluación.',
  },
  'major-20': {
    Amor: 'La trompeta llama a responder por lo pendiente. Revisa una decisión afectiva desde lo aprendido sin reducir a nadie a un error antiguo.',
    Carreira: 'El Juicio separa evaluación de condena. Revisa tu trayectoria, reconoce evidencias de cambio y responde al trabajo que todavía tiene sentido.',
    Dinheiro: 'Una elección pasada regresa para rendir cuentas. Corrige lo posible con números actuales sin permitir que la vergüenza reemplace la planificación.',
    Energia: 'El llamado toma forma al convertirse en respuesta. Elige un pendiente que merezca atención y toma la autocrítica como dato, no como identidad.',
    Saúde: 'Revisar hábitos puede ser útil sin juicio moral. Considera apoyo profesional para decisiones de salud y evalúa conductas, no tu valor personal.',
  },
  'major-21': {
    Amor: 'Dentro de la corona de laureles, el ciclo pide reconocimiento completo. Celebra lo realizado por el vínculo y nombra qué necesita cierre antes de recomenzar.',
    Carreira: 'El Mundo reúne partes antes dispersas en una entrega completa. Finaliza el detalle restante y registra el aprendizaje antes de abrir otro frente.',
    Dinheiro: 'Un cierre financiero incluye verificación, pago y margen para la transición. Completa toda la cuenta antes de tratar el próximo objetivo como disponible.',
    Energia: 'La danza dentro de la corona muestra movimiento con contorno. Termina una tarea abierta y deja que el cierre devuelva espacio mental.',
    Saúde: 'Integración significa aquí mirar rutina y apoyo como conjunto. Reconoce el progreso posible y revisa lo pendiente sin exigir perfección corporal.',
  },
};

export default pack;
