export const PACK = {
  title: 'Tu Álbum Cósmico',
  subtitle: '78 cartas, encuentros reales y patrones que solo el tiempo revela.',
  tabs: { album: 'Álbum', mirror: 'Espejo' },
  progress: ({ seen, total }) => `${seen} de ${total} reveladas`,
  progressComplete: 'La baraja entera ya pasó por tus manos.',
  progressMissing: ({ count }) =>
    count === 1 ? 'Solo 1 carta aún guarda el misterio.' : `${count} cartas aún guardan el misterio.`,
  draw: 'Hacer una tirada',
  searchPlaceholder: 'Buscar carta por nombre',
  filters: {
    all: 'Todas',
    seen: 'Reveladas',
    unseen: 'Ocultas',
    favorites: 'Favoritas',
    repeated: 'Recurrentes',
  },
  groups: { maiores: 'Arcanos Mayores', paus: 'Bastos', copas: 'Copas', espadas: 'Espadas', ouros: 'Oros' },
  noResultsTitle: 'No hay cartas aquí',
  noResultsBody: 'Prueba otro nombre o filtro. Tus cartas reveladas siguen guardadas.',
  hiddenGroupCount: ({ count }) => count === 1 ? '1 carta oculta en este grupo' : `${count} cartas ocultas en este grupo`,
  hiddenGroupHint: 'Las posiciones no se muestran para no revelar qué carta falta. Haz una tirada para descubrirla.',
  favorite: 'Guardar como favorita',
  unfavorite: 'Quitar de favoritas',
  encountersTitle: 'Tus encuentros',
  encountersCount: ({ count }) =>
    count === 1 ? 'Apareció 1 vez en tus tiradas' : `Apareció ${count} veces en tus tiradas`,
  encountersOrientation: ({ upright, reversed }) => `${upright} directa · ${reversed} invertida`,
  firstSeen: ({ date }) => `Primer encuentro registrado el ${date}`,
  lastSeen: ({ date }) => `Encuentro más reciente el ${date}`,
  legacyHistory: 'Esta carta ya estaba en tu álbum. El historial detallado empieza en el próximo encuentro.',
  legacyBaseline: 'Esta carta ya estaba en el álbum antes de esta medición. Las fechas y orientaciones empiezan en el primer encuentro registrado ahora.',
  studyTitle: 'Estudia esta carta',
  studySubtitle: 'Compara ambas orientaciones sin cambiar ninguna tirada.',
  upright: 'Directa',
  reversed: 'Invertida',
  keywords: 'Palabras clave',
  scene: 'Qué observar en la imagen',
  meaning: 'Lectura de la orientación',
  advice: 'Pregunta para reflexionar',
};
