// lib/traducoes/tarot.en.js
// Pacote de idioma INGLÊS do Tarô — mesma FORMA do pacote pt (mesmas chaves,
// mesmos placeholders {x}); a paridade é cobrada por test/tarotIdiomas.test.js.
//
// Regras que valem aqui (as mesmas do motor, lib/tarotThemes.js):
// • Tradução de SENTIDO, inglês natural de app americano — prende primeiro,
//   fonte depois; conversa, não aula.
// • O que NUNCA se traduz: nomes de obra e locus ("Book T", Pictorial Key),
//   números, datas. Títulos de carta em EN são os ORIGINAIS de Waite.
// • O verbatim de Waite (1911) já É inglês — aparece direto, sem paráfrase.
// • Linha vermelha (test/tarotIdiomas.test.js): relieve/soothe/calm/heal/
//   cure/treat/energize NÃO entram, em nenhuma forma. Nada de promessa de
//   futuro ("you will..."): o Futuro é "A vector, not a done deal."

const MAJORS = {
  'major-00': {
    name: 'The Fool',
    keywords: ['leap of faith', 'new beginnings', 'spontaneity', 'freedom'],
    upright: 'The start of a journey, innocence, and the willingness to take a risk without fearing the unknown.',
    reversed: 'Recklessness, rushed decisions, or the fear of taking the first step.',
    cena: 'the wanderer with his bundle on his shoulder and one foot on the cliff’s edge, the dog tugging at his clothes',
    conselho: 'The step asks for trust, not a guarantee — but look where you are stepping before you leap.',
    conselhoInvertido: 'Before you take the risk, ask whether it is courage or escape; if fear is what stalls you, name the fear.',
  },
  'major-01': {
    name: 'The Magician',
    keywords: ['personal power', 'skill', 'manifestation', 'action'],
    upright: 'You have every tool and resource you need to bring your goals into being.',
    reversed: 'Manipulation, wasted talent, or a lack of focus and planning.',
    cena: 'the table with the four suit symbols, one hand pointing to the sky and the other to the earth',
    conselho: 'The tools are already on your table; what is missing is choosing which one to use first.',
    conselhoInvertido: 'Check whether the promise — yours or someone else’s — has substance behind it: scattered talent manifests nothing.',
  },
  'major-02': {
    name: 'The High Priestess',
    keywords: ['intuition', 'mystery', 'inner wisdom', 'the subconscious'],
    upright: 'Trust your intuition and the secrets not yet revealed; wisdom comes from inner silence.',
    reversed: 'Secrets exposed, disconnection from your intuition, or hidden, misleading information.',
    cena: 'the guardian seated between the white and black pillars, the scroll of the law half hidden in her robe',
    conselho: 'Not everything needs to be said or decided now; wait for the piece of information that has not arrived yet.',
    conselhoInvertido: 'Either something is being kept from you, or you are ignoring what you already know inside — find out which.',
  },
  'major-03': {
    name: 'The Empress',
    keywords: ['abundance', 'fertility', 'nature', 'creativity'],
    upright: 'Abundance, fertile creativity, and connection with nature are flourishing in your life.',
    reversed: 'Creative block, excessive dependence, or neglecting yourself.',
    cena: 'the cushioned throne in the field of ripe wheat, scepter in hand and the shield of Venus at her side',
    conselho: 'Let it grow in the time it needs — here, tending is also producing.',
    conselhoInvertido: 'Caring for everyone and nothing of your own dries up the spring; pull some of it back inward.',
  },
  'major-04': {
    name: 'The Emperor',
    keywords: ['authority', 'structure', 'control', 'leadership'],
    upright: 'Structure, authority, and steady leadership bring order and security.',
    reversed: 'Excessive rigidity, authoritarianism, or a lack of discipline and control.',
    cena: 'the stone throne with ram heads, on a dry mountain with nothing green around it',
    conselho: 'Set the rule and the limit before moving on — here, structure is protection, not prison.',
    conselhoInvertido: 'Too much rigidity and no frame at all come to the same thing: nothing holds.',
  },
  'major-05': {
    name: 'The Hierophant',
    keywords: ['tradition', 'conformity', 'institutional spirituality', 'teaching'],
    upright: 'Tradition, spiritual guidance, and established values light the way.',
    reversed: 'Rebellion against convention, dogmatism, or the questioning of traditional beliefs.',
    cena: 'the master between two pillars blessing two disciples, the crossed keys at his feet',
    conselho: 'It is worth consulting someone who has walked this road before inventing your own.',
    conselhoInvertido: 'The inherited rule may no longer fit — question it, but know what you are leaving behind.',
  },
  'major-06': {
    name: 'The Lovers',
    keywords: ['choices', 'alignment of values', 'love', 'harmony'],
    upright: 'Union, true love, and an important choice aligned with your values.',
    reversed: 'Disharmony, misaligned values, or conflicting choices in love.',
    cena: 'the angel above two figures, between the tree of knowledge and the tree of life: the instant before the choice',
    conselho: 'Choose by what you value, not by what is easiest — and choose one thing only.',
    conselhoInvertido: 'If the decision has stalled, two of your values are in conflict; name them both before deciding.',
  },
  'major-07': {
    name: 'The Chariot',
    keywords: ['determination', 'will', 'victory', 'control'],
    upright: 'Victory through determination, focus, and command over opposing forces.',
    reversed: 'Lack of direction, aggression, or losing control of the course.',
    cena: 'the driver standing between two sphinxes of opposite colors, no reins in his hands',
    conselho: 'Hold the direction by will, not by force — the two sphinxes pull opposite ways.',
    conselhoInvertido: 'Without a set course, energy turns into agitation; stop and say where to before you accelerate.',
  },
  'major-08': {
    name: 'Strength',
    keywords: ['courage', 'patience', 'compassion', 'inner strength'],
    upright: 'Serene courage and compassion overcome any obstacle with patience.',
    reversed: 'Insecurity, self-doubt, or brute force used instead of gentleness.',
    cena: 'the woman closing the lion’s mouth with her bare hands, without violence, under the symbol of infinity',
    conselho: 'Firmness with gentleness bends what brute force only provokes.',
    conselhoInvertido: 'The doubt about yourself is doing the job the obstacle could not.',
  },
  'major-09': {
    name: 'The Hermit',
    keywords: ['introspection', 'inner search', 'solitude', 'guidance'],
    upright: 'A time of introspection and of searching for answers within yourself.',
    reversed: 'Excessive isolation, unwanted loneliness, or refusing to ask for help.',
    cena: 'the old man atop the mountain with a star inside his lantern, lighting only the next step',
    conselho: 'Withdrawing for a while here is method, not escape — the lantern shows one step at a time.',
    conselhoInvertido: 'The retreat has become isolation; ask a specific person for help, not the world in general.',
  },
  'major-10': {
    name: 'Wheel of Fortune',
    keywords: ['cycles', 'destiny', 'change', 'luck'],
    upright: 'A turning cycle brings new opportunities guided by destiny.',
    reversed: 'Perceived bad luck, resistance to change, or negative cycles repeating.',
    cena: 'the wheel turning in the sky with the four creatures in the corners, each reading its own book',
    conselho: 'What turns does not ask for control, it asks for position — see where in the turn you are.',
    conselhoInvertido: 'If the same cycle keeps repeating, look for your part in it: that is where the choice lives.',
  },
  'major-11': {
    name: 'Justice',
    keywords: ['truth', 'balance', 'law', 'cause and effect'],
    upright: 'Balance, truth, and impartial justice guide decisions and their outcomes.',
    reversed: 'Injustice, dishonesty, or refusing responsibility for your own actions.',
    cena: 'the figure seated with the sword raised in one hand and the scales in the other, between the curtains',
    conselho: 'Look at the fact before the feeling, and own your share of the bill.',
    conselhoInvertido: 'There is a real imbalance; before accusing, check what part of it is yours.',
  },
  'major-12': {
    name: 'The Hanged Man',
    keywords: ['pause', 'surrender', 'new perspective', 'sacrifice'],
    upright: 'A voluntary pause reveals a new perspective on the situation.',
    reversed: 'Resistance to a necessary sacrifice, stagnation, or unwanted delays.',
    cena: 'the man hanging upside down by one foot, serene, a halo around his head',
    conselho: 'The pause is the work right now — pushing only tightens the knot.',
    conselhoInvertido: 'You have been hanging too long with nothing changing: either surrender for real, or come down.',
  },
  'major-13': {
    name: 'Death',
    keywords: ['transformation', 'end of a cycle', 'transition', 'renewal'],
    upright: 'The end of a cycle opening space for deep transformation and renewal.',
    reversed: 'Resistance to change, stagnation, or fear of closing a cycle that needs to end.',
    cena: 'the armored knight riding past with the banner of the white rose, the sun rising between two towers in the background',
    conselho: 'Something has truly ended; the energy spent holding on is the energy the next thing lacks.',
    conselhoInvertido: 'Holding on to what has already ended does not bring it back — it only postpones the grief and charges interest.',
  },
  'major-14': {
    name: 'Temperance',
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    upright: 'Balance and moderation bring harmony between opposing forces.',
    reversed: 'Excess, imbalance, or a lack of patience and long-term vision.',
    cena: 'the angel with one foot in the water and one on land, pouring liquid from one cup to the other',
    conselho: 'Mix a little at a time: here the right dose matters more than the decision.',
    conselhoInvertido: 'Some excess is unbalancing the rest; pick just one and reduce that.',
  },
  'major-15': {
    name: 'The Devil',
    keywords: ['attachment', 'vices', 'materialism', 'shadow'],
    upright: 'Attachment to limiting patterns, vices, or excessive materialism is holding you captive.',
    reversed: 'Release from self-imposed chains and the recognition of harmful patterns.',
    cena: 'the chained couple at the block — with chains loose enough to slip off over the head',
    conselho: 'Look at the chain and what it gives you in return; without that, the pattern goes on.',
    conselhoInvertido: 'The chain is loosening — name what you can already let go of today.',
  },
  'major-16': {
    name: 'The Tower',
    keywords: ['sudden rupture', 'revelation', 'chaos', 'awakening'],
    upright: 'A sudden, revealing rupture brings down structures that no longer held.',
    reversed: 'Dodging an unavoidable change, disaster postponed, or fear of transformation.',
    cena: 'the lightning bolt tearing the crown off the top of the tower and the two figures falling',
    conselho: 'What fell was already cracked; gather what was true and do not rebuild it the same.',
    conselhoInvertido: 'The fall is being postponed, or lived out inwardly in silence — postponing here charges interest.',
  },
  'major-17': {
    name: 'The Star',
    keywords: ['hope', 'faith', 'renewal', 'inspiration'],
    upright: 'Hope, inspiration, and renewal after a hard season.',
    reversed: 'Despair, loss of faith, or disconnection from your own inspiration.',
    cena: 'the woman kneeling, pouring two jugs, one into the pool and one onto the earth, under eight stars',
    conselho: 'Trust enough to keep watering the ground: recovery is slow and it is real.',
    conselhoInvertido: 'Faith has dropped — find the small, concrete thing that still works and start there.',
  },
  'major-18': {
    name: 'The Moon',
    keywords: ['illusion', 'intuition', 'fear', 'the subconscious'],
    upright: 'Deep intuition surfaces, but illusions and fears still blur the picture.',
    reversed: 'Confusion clearing, fears overcome, or the truth coming to light.',
    cena: 'the path between two towers, the dog and the wolf howling and the crayfish crawling out of the water',
    conselho: 'Do not decide in the dark; wait for it to clear or ask for a second pair of eyes.',
    conselhoInvertido: 'What frightened you is taking shape — the fear was bigger than the fact.',
  },
  'major-19': {
    name: 'The Sun',
    keywords: ['joy', 'success', 'vitality', 'clarity'],
    upright: 'Success, genuine joy, and full vitality light up the road.',
    reversed: 'Overblown optimism, success momentarily dimmed, or a lack of clarity.',
    cena: 'the child on the white horse under the sunflowers, the open-faced sun above',
    conselho: 'Let it be simple and visible — not everything needs complication to have worth.',
    conselhoInvertido: 'The joy is there, just overshadowed; look for what is blocking the light.',
  },
  'major-20': {
    name: 'Judgement',
    keywords: ['rebirth', 'inner calling', 'reckoning', 'absolution'],
    upright: 'An inner calling invites you to an awakening and a personal rebirth.',
    reversed: 'Excessive self-criticism, doubt over past decisions, or resisting the call.',
    cena: 'the angel with the trumpet and the figures rising from their coffins, arms open',
    conselho: 'An old calling has returned; answering is deciding, not waiting for a better sign.',
    conselhoInvertido: 'Self-criticism is not evaluation: judge the act, not the person you are.',
  },
  'major-21': {
    name: 'The World',
    keywords: ['completion', 'achievement', 'integration', 'wholeness'],
    upright: 'Full achievement and the successful closing of a great life cycle.',
    reversed: 'An unfinished cycle, a sense of stagnation, or the search for closure.',
    cena: 'the figure dancing inside the laurel wreath, with the four creatures in the corners',
    conselho: 'Close the cycle completely before opening the next — acknowledging the end is part of it.',
    conselhoInvertido: 'One detail is missing to close it, and that detail is holding everything; find out which it is.',
  },
};

// Menores: keywords/upright/reversed espelham MINOR_MEANINGS; cena/conselho/
// conselhoInvertido espelham CARD_DEPTH (lib/tarotDeck.js), carta a carta.
const MINORS = {
  paus: {
    1: { keywords: ['beginning', 'inspiration', 'potential'], upright: 'A new start, creative inspiration, and potential ready to move into action.', reversed: 'Delays, lack of direction, or creative energy stalled.', cena: 'the hand coming out of the cloud holding a staff still sprouting leaves', conselho: 'The spark is real, but it is still a spark — take the first concrete step today.', conselhoInvertido: 'The will is there and nothing moves: shrink the project to the smallest possible step.' },
    2: { keywords: ['planning', 'decision', 'expansion'], upright: 'Careful planning and decisions about the future open new horizons.', reversed: 'Fear of the unknown or no plan for expanding.', cena: 'the man atop the castle with the globe in his hand, watching the sea, one staff fixed to the wall and one in his hand', conselho: 'Choose between the map and the world: more planning is no substitute for deciding.', conselhoInvertido: 'The fear of the unknown is dressed up as "it is not time yet".' },
    3: { keywords: ['foresight', 'expansion', 'results'], upright: 'Expansion and long-range vision bring results from efforts already underway.', reversed: 'Delays or unexpected obstacles in plans already moving.', cena: 'the figure seen from behind on the cliff, three staves planted, watching the ships set out', conselho: 'What you launched is already on its way; now you follow it, you do not start over.', conselhoInvertido: 'The delay is in the schedule, not the project — revise the expectation before revising the plan.' },
    4: { keywords: ['celebration', 'harmony', 'home'], upright: 'Celebration, harmony, and a moment worth marking at home or in the community.', reversed: 'Instability at home or a celebration postponed.', cena: 'four flowering staves forming a garlanded gateway, with the feast going on behind', conselho: 'Something has been built and has not been acknowledged yet — acknowledge it before moving on.', conselhoInvertido: 'Either the foundation is shaky, or the celebration keeps being postponed; tend the house first.' },
    5: { keywords: ['conflict', 'competition', 'tension'], upright: 'Conflict, competition, and tension between different wills or interests.', reversed: 'Inner conflict, or the urge to dodge a confrontation that is needed.', cena: 'five youths with staves raised in a confused skirmish, more drill than war', conselho: 'This is a skirmish, not a war: referee the agreement instead of winning the argument.', conselhoInvertido: 'The conflict has turned inward — name what you have not said.' },
    6: { keywords: ['victory', 'recognition', 'success'], upright: 'Victory and public recognition after a successful effort.', reversed: 'Falling popularity, arrogance, or recognition overdue.', cena: 'the laurel-crowned rider parading among those on foot', conselho: 'Accept the recognition without convincing yourself it is permanent.', conselhoInvertido: 'If the credit did not come, check what was delivered before blaming the audience.' },
    7: { keywords: ['defense', 'perseverance', 'challenge'], upright: 'A firm defense of your own position and perseverance in the face of challenge.', reversed: 'Feeling overwhelmed, or giving in to the pressure of others.', cena: 'the figure on the high ground defending his position against six staves rising', conselho: 'The position is worth defending, as long as it is still yours — check that before spending the strength.', conselhoInvertido: 'The pressure won by exhaustion; pick one front and let the others go.' },
    8: { keywords: ['speed', 'movement', 'progress'], upright: 'Fast action, movement, and accelerating progress toward the goal.', reversed: 'Delays, frustration, or something dragging on longer than it should.', cena: 'eight staves crossing the open sky in mid flight, no one in the scene', conselho: 'Things move fast now: answer at their pace instead of holding back.', conselhoInvertido: 'What is stuck needs one simple unblocking, not a new plan.' },
    9: { keywords: ['resilience', 'caution', 'persistence'], upright: 'Resilience and caution gather the last of your strength before the final win.', reversed: 'Exhaustion, excessive stubbornness, or strength worn down to nothing.', cena: 'the man wounded at the head, leaning on his staff, eight staves lined up behind him like a fence', conselho: 'You are wounded and still standing — just do not confuse vigilance with distrusting everything.', conselhoInvertido: 'The raised guard has become a wall; check whether there is still an enemy outside.' },
    10: { keywords: ['overload', 'burden', 'responsibility'], upright: 'An overload of responsibilities and a heavy burden to carry.', reversed: 'Dropping needless loads, delegating, or admitting exhaustion.', cena: 'the figure bent over carrying ten staves that block his own view of the city just ahead', conselho: 'The burden needs to be set down, not carried better: drop a part or share it.', conselhoInvertido: 'You are already letting go of the load — choose which piece goes first and do not pick up another in its place.' },
    11: { keywords: ['enthusiasm', 'curiosity', 'message'], upright: 'An eager messenger, curiosity, and fresh creative ideas arriving.', reversed: 'Lack of direction, procrastination, or unwelcome news.', cena: 'the youth standing in the desert, studying the top of his staff as if reading news', conselho: 'A new idea or piece of news has arrived; investigate before announcing.', conselhoInvertido: 'Plenty of ideas and no start: pick one and give it a deadline.' },
    12: { keywords: ['action', 'adventure', 'impulsiveness'], upright: 'Impulsive action, passion, and a readiness for journeys and adventure.', reversed: 'Excessive impulsiveness, frustration, or projects dropped midway.', cena: 'the rearing horse and the armored rider charging off', conselho: 'A good hour to set out — with the usual caveat: know where to.', conselhoInvertido: 'Impulse without direction leaves projects half done; finish one before the next.' },
    13: { keywords: ['confidence', 'determination', 'independence'], upright: 'Magnetic confidence, determination, and unshakeable independence.', reversed: 'Jealousy, insecurity, or domineering behavior.', cena: 'the queen facing forward, sunflower in hand and the black cat sitting at her feet', conselho: 'Hold what is yours with warmth, without needing to convince anyone.', conselhoInvertido: 'If insecurity does the talking, it will come out sounding like control — watch for that.' },
    14: { keywords: ['leadership', 'vision', 'charisma'], upright: 'Visionary leadership, entrepreneurial courage, and natural charisma.', reversed: 'Impulsiveness, arrogance, or inflated expectations of others.', cena: 'the king slightly turned on his salamander throne, staff firm in hand', conselho: 'Lead by vision and delegate the execution; centralizing here jams everything.', conselhoInvertido: 'The promise has grown bigger than the delivery — resize what you promised.' },
  },
  copas: {
    1: { keywords: ['new love', 'intuition', 'emotional opening'], upright: 'New love, emotional opening, and fertile intuition overflowing.', reversed: 'Emotional block, unreturned love, or a sense of inner emptiness.', cena: 'the hand in the cloud offering the cup with five streams, the dove descending', conselho: 'An emotional opening is available; receiving is also an act.', conselhoInvertido: 'The channel closed for protection — do not force it, but notice what closed it.' },
    2: { keywords: ['union', 'partnership', 'attraction'], upright: 'Union, partnership, and mutual attraction building a true connection.', reversed: 'Imbalance in the relationship, a break, or discord between the two sides.', cena: 'the two facing each other and exchanging cups beneath the caduceus and the lion’s head', conselho: 'A bond between equals needs its terms said out loud, not assumed.', conselhoInvertido: 'The exchange is uneven; say what the imbalance is instead of compensating alone.' },
    3: { keywords: ['celebration', 'friendship', 'community'], upright: 'Celebration, friendship, and shared joy in good company.', reversed: 'Excess, gossip, or social isolation.', cena: 'the three dancing in a circle with cups raised, in the middle of the harvest', conselho: 'Celebrate with those who stood by you — bonds are kept in celebration too.', conselhoInvertido: 'Excess or gossip is corroding the group; step back a little.' },
    4: { keywords: ['apathy', 'contemplation', 'missed opportunity'], upright: 'Apathy and contemplation while opportunities pass unnoticed.', reversed: 'Waking up to new possibilities and moving past the boredom.', cena: 'the young man with arms crossed under the tree, ignoring the fourth cup the cloud offers', conselho: 'An offer is being held out and you are not looking — notice what has already arrived.', conselhoInvertido: 'The boredom is passing; start accepting the small invitations again.' },
    5: { keywords: ['loss', 'grief', 'regret'], upright: 'Loss, grief, and a gaze fixed on what is no longer there.', reversed: 'Acceptance, forgiveness, and the readiness to move on.', cena: 'the figure in the black cloak staring at the three fallen cups, not seeing the two still standing behind her', conselho: 'Three cups fell and two still stand — turn toward the ones left, without rushing the grief.', conselhoInvertido: 'Forgiveness is starting to fit; move on without demanding that you forget.' },
    6: { keywords: ['nostalgia', 'memories', 'childhood'], upright: 'Nostalgia, good memories, and reunions with the past.', reversed: 'Clinging to the past, or idealizing days already gone.', cena: 'the child handing the flowered cup to another, in the courtyard of the old house', conselho: 'Memory is good company, not an address: visit without moving in.', conselhoInvertido: 'Idealizing the past is keeping the present from taking on color.' },
    7: { keywords: ['fantasy', 'illusion', 'choices'], upright: 'Fantasies and illusory options make the choices confusing.', reversed: 'Clarity about one real choice, with the illusions finally dissolved.', cena: 'the seven cups in the cloud, each holding a different vision, and only one with something real inside', conselho: 'Of the seven visions, one is real — cut the pretty, empty options first.', conselhoInvertido: 'The fog has lifted: choose now, while it is still clear.' },
    8: { keywords: ['walking away', 'search', 'purpose'], upright: 'Walking away from what no longer feeds you, in search of a larger purpose.', reversed: 'Fear of moving on, or staying put out of comfort.', cena: 'the figure walking away under the moon, leaving eight cups stacked with a gap in the middle', conselho: 'Leaving what no longer feeds you is a chosen loss — and sometimes it is the way.', conselhoInvertido: 'Staying out of comfort is also a choice; name what is holding you.' },
    9: { keywords: ['satisfaction', 'wish fulfilled', 'contentment'], upright: 'Satisfaction, contentment, and an important wish fulfilled.', reversed: 'Excess, shallow satisfaction, or hollow pride.', cena: 'the satisfied host with arms crossed, the nine cups lined up on the counter behind him', conselho: 'The wish came true; check whether it was still the right wish.', conselhoInvertido: 'Showcase satisfaction does not hold — ask what you really wanted.' },
    10: { keywords: ['happiness', 'family', 'harmony'], upright: 'Family happiness and full, lasting emotional harmony.', reversed: 'Family conflict, or values out of line within the home.', cena: 'the rainbow of ten cups over the couple and the two children dancing', conselho: 'A home’s harmony is tended on ordinary days, not just in photos.', conselhoInvertido: 'There is a misalignment of values inside the home; face it before it becomes routine.' },
    11: { keywords: ['message', 'intuition', 'creativity'], upright: 'Intuitive messages and emotional creativity bringing news to the heart.', reversed: 'Emotional immaturity, disappointment, or a creative block.', cena: 'the youth looking, surprised, at the fish that appeared inside the cup', conselho: 'An emotional or creative message is surfacing; give it room even before you understand it.', conselhoInvertido: 'Emotional immaturity is getting in the way — yours or theirs; do not take everything personally.' },
    12: { keywords: ['romance', 'invitation', 'idealism'], upright: 'Romance, invitations, and the willingness to follow the heart.', reversed: 'Moodiness, empty promises, or romantic disappointment.', cena: 'the knight advancing slowly along the river, cup held out before him', conselho: 'The invitation is sincere; check whether the proposal matches the charm.', conselhoInvertido: 'A pretty promise without a date is just a promise — ask for the date.' },
    13: { keywords: ['empathy', 'intuition', 'care'], upright: 'Empathy, sharp intuition, and deep emotional care for others.', reversed: 'Emotional insecurity, dependence, or oversensitivity.', cena: 'the queen by the sea, absorbed in the closed, ornate cup only she sees inside', conselho: 'Your emotional reading is sharp; care for yourself with the same care you offer.', conselhoInvertido: 'Absorbing other people’s feelings has become a weight — redraw the line between you and them.' },
    14: { keywords: ['emotional balance', 'wisdom', 'maturity'], upright: 'Emotional balance, compassionate wisdom, and maturity of feeling.', reversed: 'Emotional instability, manipulation, or coldness of heart.', cena: 'the king on his throne amid the rough sea, without getting wet', conselho: 'Feel and decide in the same motion: maturity here is neither drowning nor freezing.', conselhoInvertido: 'Coldness or emotional blackmail is in play; check which side it is on.' },
  },
  espadas: {
    1: { keywords: ['clarity', 'truth', 'new idea'], upright: 'Mental clarity, truth, and a powerful new idea arriving.', reversed: 'Confusion, distorted information, or decisions made in haste.', cena: 'the hand in the cloud raising the sword, with the crown and the branch hanging from its tip', conselho: 'The truth is available and cuts both ways — use it once, with precision.', conselhoInvertido: 'The information is distorted; confirm it at the source before acting.' },
    2: { keywords: ['stalemate', 'indecision', 'tense balance'], upright: 'Stalemate and indecision before a difficult choice.', reversed: 'Information overload, a forced decision, or running from the truth.', cena: 'the blindfolded woman, her back to the sea, balancing two crossed swords over her chest', conselho: 'Take off the blindfold before deciding: the deadlock is missing data, not missing courage.', conselhoInvertido: 'The decision is being forced by the deadline; choose the criterion before choosing the side.' },
    3: { keywords: ['pain', 'betrayal', 'heartbreak'], upright: 'Emotional pain, betrayal, and the feeling of a broken heart.', reversed: 'Forgiveness and rebuilding: the pain gives way little by little.', cena: 'the three swords piercing the heart, under the rain and the closed sky', conselho: 'The pain is real and naming it is today’s work — do not rush to make it positive.', conselhoInvertido: 'The recovery has begun, little by little; do not mistake a scar for an open wound.' },
    4: { keywords: ['rest', 'recovery', 'pause'], upright: 'Rest and recovery needed after a period of strain.', reversed: 'Burnout, a forced return to action, or a pause stretched too long.', cena: 'the knight lying on stone in the chapel, three swords on the wall and one beneath the body', conselho: 'Resting here is part of the strategy; the battle continues afterward.', conselhoInvertido: 'Either you stop now, or the body stops for you.' },
    5: { keywords: ['conflict', 'defeat', 'dispute'], upright: 'Conflict, and a victory won at the cost of something that mattered.', reversed: 'Reconciliation and the willingness to leave grudges behind.', cena: 'the winner gathering the swords while the other two walk away with their backs turned', conselho: 'Check the price of the victory before celebrating — it may not be worth what it cost.', conselhoInvertido: 'There is room for reconciliation; someone has to take the first step and it can be you.' },
    6: { keywords: ['transition', 'movement', 'leaving behind'], upright: 'Transition and movement toward quieter waters, leaving hardship astern.', reversed: 'Resistance to change, or difficulty moving forward.', cena: 'the boatman carrying the woman and child to the other shore, six swords planted in the bow', conselho: 'The crossing has already begun: take the essentials and accept that the new shore feels strange at first.', conselhoInvertido: 'You want to go and you are still moored — see what is still tied to the other shore.' },
    7: { keywords: ['strategy', 'deception', 'stealth'], upright: 'Strategy and discreet action, sometimes involving some kind of deception.', reversed: 'Confession, regret, or lies coming into the open.', cena: 'the figure slipping out of the camp on tiptoe with five swords, leaving two planted', conselho: 'Discreet strategy can be legitimate; if it must be hidden from everyone, it is not.', conselhoInvertido: 'It is time to confess or give it back, before it surfaces some other way.' },
    8: { keywords: ['imprisonment', 'limitation', 'fear'], upright: 'A feeling of imprisonment among limits that are, in truth, self-imposed.', reversed: 'Release, a new perspective, and the breaking of limiting mental patterns.', cena: 'the woman bound and blindfolded among eight swords, with the ropes loose and the ground clear ahead', conselho: 'The ropes are loose and the ground is clear: the prison is more mental than real.', conselhoInvertido: 'You have begun to see the way out; take one small step and confirm it holds.' },
    9: { keywords: ['anxiety', 'anguish', 'nightmare'], upright: 'Anxiety, nightmares, and mental anguish stealing your sleep.', reversed: 'The anxiety easing little by little, or a despair still kept hidden.', cena: 'the figure sitting up in bed in the dark, face in hands, nine swords lined on the wall', conselho: 'The suffering is bigger in your head than in the fact — check the fact in the morning, awake.', conselhoInvertido: 'The anguish is easing, or it is hidden; tell someone and find out which.' },
    10: { keywords: ['ending', 'collapse', 'rock bottom'], upright: 'A painful ending, collapse, and the sense of having hit the lowest point.', reversed: 'Recovery, and the resolve not to repeat the same cycle.', cena: 'the figure lying face down with ten swords in the back, and the sky already lightening on the horizon', conselho: 'Rock bottom has one advantage: from here the only way is up, and the day is already breaking.', conselhoInvertido: 'You survived — the care now is not to replay the same script out of habit.' },
    11: { keywords: ['curiosity', 'vigilance', 'ideas'], upright: 'Intellectual curiosity, watchfulness, and new ideas taking shape.', reversed: 'Gossip, mistaken information, or careless words.', cena: 'the youth standing on the windy hilltop, sword raised, glancing over his shoulder', conselho: 'Curiosity and vigilance are useful; observing is not surveilling everyone.', conselhoInvertido: 'Gossip and twisted information are circulating: do not pass on what you have not confirmed.' },
    12: { keywords: ['swift action', 'ambition', 'impulsiveness'], upright: 'Fast, direct action driven by intellectual ambition.', reversed: 'Impulsiveness, recklessness, or aggression in word and deed.', cena: 'the knight charging against the wind, sword pointed ahead', conselho: 'Speed is the strength here; just check whether you are going or fleeing.', conselhoInvertido: 'The rush is becoming a stampede — reread before you send.' },
    13: { keywords: ['clarity', 'honesty', 'independence'], upright: 'Mental clarity, direct honesty, and intellectual independence.', reversed: 'Excessive coldness, cutting criticism, or emotional isolation.', cena: 'the queen in profile on the throne of clouds, sword raised and the open hand extended in invitation', conselho: 'Speak clearly and without cruelty: honesty does not need to hurt on purpose.', conselhoInvertido: 'The criticism is cutting the people you love; ask what pain it comes from.' },
    14: { keywords: ['authority', 'ethics', 'intellect'], upright: 'Intellectual authority, solid ethics, and the pursuit of truth.', reversed: 'Mental manipulation, rigidity, or abuse of power.', cena: 'the king facing forward on the throne, sword slightly tilted and his gaze crossing whoever approaches', conselho: 'Decide by the criterion, not the mood — and write the criterion down.', conselhoInvertido: 'An argument being used as power; if you are on the strong side, take a step back.' },
  },
  ouros: {
    1: { keywords: ['opportunity', 'prosperity', 'new material venture'], upright: 'A new material opportunity and prosperity in the making.', reversed: 'A missed opportunity or financial instability.', cena: 'the hand in the cloud holding the pentacle over the flowering garden, with the hedge archway opening the path', conselho: 'A concrete material opportunity has arrived; take it as a seed, not a harvest.', conselhoInvertido: 'Either the opportunity slipped by, or the foundation was not ready — find out which.' },
    2: { keywords: ['balance', 'adaptation', 'priorities'], upright: 'Balance between priorities and good footing amid change.', reversed: 'Financial disarray or an overload of commitments.', cena: 'the juggler balancing two pentacles on the figure-eight ribbon, ships on the rough sea behind him', conselho: 'Balancing two commitments is possible today; a third brings down both.', conselhoInvertido: 'The juggler is tired: cut one commitment instead of speeding up.' },
    3: { keywords: ['collaboration', 'teamwork', 'recognition'], upright: 'Teamwork, collaboration, and well-earned professional recognition.', reversed: 'Lack of cooperation, or work delivered below standard.', cena: 'the craftsman on the scaffold explaining the work to the monk and the master builder', conselho: 'Good work here is agreed work — align what each one delivers.', conselhoInvertido: 'The agreeing was skipped before the doing; the fault is coordination, not effort.' },
    4: { keywords: ['security', 'control', 'material attachment'], upright: 'Material security, control, and the wish to keep what has been won.', reversed: 'Greed, fear of loss, or excessive materialism.', cena: 'the crowned figure clutching one pentacle, one on his head and one under each foot, the city behind', conselho: 'Saving makes sense; gripping everything with both hands is what keeps you from receiving.', conselhoInvertido: 'Either the fear of losing has loosened, or the control has tightened — check which.' },
    5: { keywords: ['hardship', 'exclusion', 'financial loss'], upright: 'Financial hardship and the feeling of being left out in a difficult hour.', reversed: 'Financial recovery and the end of a season of scarcity.', cena: 'the two wanderers passing through the snow beneath the lit stained-glass window they do not look at', conselho: 'Support is missing and help is a few steps away, behind the lit window: ask.', conselhoInvertido: 'The scarcity is passing; accept the help that comes without reading it as defeat.' },
    6: { keywords: ['generosity', 'mutual help', 'balance'], upright: 'Generosity and mutual help create balance between giving and receiving.', reversed: 'Debts, dependence, or generosity with strings attached.', cena: 'the merchant weighing on the scales and handing coins to two kneeling beggars', conselho: 'Giving and receiving need to be clear — whoever holds the scales sets the terms.', conselhoInvertido: 'Check whether the generosity has a price built in, on one side or the other.' },
    7: { keywords: ['patience', 'assessment', 'investment'], upright: 'Patience to assess investments that still need time to ripen.', reversed: 'Impatience, or effort that seems to bring no return.', cena: 'the farmer leaning on his hoe, gazing at the seven pentacles on the bush he has not yet harvested', conselho: 'The crop is not ready yet; assessing now beats picking it green.', conselhoInvertido: 'If the effort has gone unrewarded too long, the problem may be the crop, not the patience.' },
    8: { keywords: ['dedication', 'learning', 'skill'], upright: 'Dedication, steady learning, and the refinement of a skill.', reversed: 'Perfectionism, work without clear purpose, or professional stagnation.', cena: 'the craftsman seated, chiseling the eighth pentacle, the finished ones hung beside him', conselho: 'Repetition is the method here: the skill is built by doing it again.', conselhoInvertido: 'Perfectionism or meaningless work — either way, what you make is missing a destination.' },
    9: { keywords: ['independence', 'self-sufficiency', 'achievement'], upright: 'Financial independence, self-sufficiency, and achievements enjoyed with pleasure.', reversed: 'Financial dependence, or insecurity despite apparent success.', cena: 'the woman in her own vineyard garden, the hooded falcon perched on her hand', conselho: 'You built your own garden; enjoying it is part of the work too.', conselhoInvertido: 'The independence is more in the looks than in the ledger; look at the numbers.' },
    10: { keywords: ['wealth', 'legacy', 'stability'], upright: 'Lasting wealth, family legacy, and stability built over the long run.', reversed: 'Family financial instability, or disputes over an inheritance.', cena: 'the three generations under the city arch, the dogs at the old man’s feet and the ten pentacles scattered through the scene', conselho: 'Think long term and of who comes after — legacy is built by shared decision.', conselhoInvertido: 'There is a dispute or instability at the family base; fix the agreement, not the person.' },
    11: { keywords: ['opportunity', 'study', 'practicality'], upright: 'A new opportunity for study or work, with a practical eye on the next steps.', reversed: 'Lack of planning, procrastination, or opportunities wasted.', cena: 'the youth in the field holding the pentacle before his eyes, completely absorbed', conselho: 'A new study or job starts slowly; take the beginning as apprenticeship.', conselhoInvertido: 'Planning without starting is procrastination with a pretty name.' },
    12: { keywords: ['method', 'reliability', 'steadiness'], upright: 'Methodical work, reliability, and steady effort toward the result.', reversed: 'Stagnation, stubbornness, or routine taken to the extreme.', cena: 'the knight halted in the plowed field, the heavy horse motionless, pentacle in hand', conselho: 'Slow and steady is literally the reading: constancy beats brilliance here.', conselhoInvertido: 'The routine has become stagnation; change one small variable.' },
    13: { keywords: ['practicality', 'care', 'abundance'], upright: 'Practicality, care for the material and the emotional, and generous abundance.', reversed: 'Neglect of the finances, or of your own self-care.', cena: 'the queen on the flowered throne gazing at the pentacle in her lap as if tending something alive', conselho: 'Caring for the concrete — body, home, money — is emotional care too.', conselhoInvertido: 'You have cared for everything but yourself; the self-care here is material, not motivational.' },
    14: { keywords: ['material success', 'leadership', 'security'], upright: 'Consolidated material success, steady leadership, and established abundance.', reversed: 'Excessive materialism, financial rigidity, or authoritarianism.', cena: 'the king on the throne of grape clusters and bull heads, the castle already built behind him', conselho: 'The foundation is built; manage it with generosity instead of hoarding.', conselhoInvertido: 'Financial rigidity or authoritarianism: is the resource serving you, or the other way around?' },
  },
};

// Golden Dawn em inglês é o ORIGINAL — os títulos abaixo são os do Book T,
// não tradução nossa.
const SUIT_NAME = { paus: 'Wands', copas: 'Cups', espadas: 'Swords', ouros: 'Pentacles' };
const RANK_NAME = {
  1: 'Ace', 2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven',
  8: 'Eight', 9: 'Nine', 10: 'Ten', 11: 'Page', 12: 'Knight', 13: 'Queen', 14: 'King',
};
const SUIT_ELEMENT = { paus: 'Fire', copas: 'Water', espadas: 'Air', ouros: 'Earth' };
const COURT_ELEMENT = { 11: 'Earth', 12: 'Air', 13: 'Water', 14: 'Fire' };
const DECANS = {
  paus: {
    2: ['Mars in Aries', 'Lord of Dominion'],
    3: ['Sun in Aries', 'Lord of Established Strength'],
    4: ['Venus in Aries', 'Lord of Perfected Work'],
    5: ['Saturn in Leo', 'Lord of Strife'],
    6: ['Jupiter in Leo', 'Lord of Victory'],
    7: ['Mars in Leo', 'Lord of Valour'],
    8: ['Mercury in Sagittarius', 'Lord of Swiftness'],
    9: ['Moon in Sagittarius', 'Lord of Great Strength'],
    10: ['Saturn in Sagittarius', 'Lord of Oppression'],
  },
  copas: {
    2: ['Venus in Cancer', 'Lord of Love'],
    3: ['Mercury in Cancer', 'Lord of Abundance'],
    4: ['Moon in Cancer', 'Lord of Blended Pleasure'],
    5: ['Mars in Scorpio', 'Lord of Loss in Pleasure'],
    6: ['Sun in Scorpio', 'Lord of Pleasure'],
    7: ['Venus in Scorpio', 'Lord of Illusionary Success'],
    8: ['Saturn in Pisces', 'Lord of Abandoned Success'],
    9: ['Jupiter in Pisces', 'Lord of Material Happiness'],
    10: ['Mars in Pisces', 'Lord of Perfected Success'],
  },
  espadas: {
    2: ['Moon in Libra', 'Lord of Peace Restored'],
    3: ['Saturn in Libra', 'Lord of Sorrow'],
    4: ['Jupiter in Libra', 'Lord of Rest from Strife'],
    5: ['Venus in Aquarius', 'Lord of Defeat'],
    6: ['Mercury in Aquarius', 'Lord of Earned Success'],
    7: ['Moon in Aquarius', 'Lord of Unstable Effort'],
    8: ['Jupiter in Gemini', 'Lord of Shortened Force'],
    9: ['Mars in Gemini', 'Lord of Despair and Cruelty'],
    10: ['Sun in Gemini', 'Lord of Ruin'],
  },
  ouros: {
    2: ['Jupiter in Capricorn', 'Lord of Harmonious Change'],
    3: ['Mars in Capricorn', 'Lord of Material Works'],
    4: ['Sun in Capricorn', 'Lord of Earthly Power'],
    5: ['Mercury in Taurus', 'Lord of Material Trouble'],
    6: ['Moon in Taurus', 'Lord of Material Success'],
    7: ['Saturn in Taurus', 'Lord of Success Unfulfilled'],
    8: ['Sun in Virgo', 'Lord of Prudence'],
    9: ['Venus in Virgo', 'Lord of Material Gain'],
    10: ['Mercury in Virgo', 'Lord of Wealth'],
  },
};

function astroFor(suitKey, number) {
  if (number === 1) return `Root of the Powers of ${SUIT_ELEMENT[suitKey]}`;
  if (number >= 11) return `${COURT_ELEMENT[number]} of ${SUIT_ELEMENT[suitKey]}`;
  const entry = DECANS[suitKey]?.[number];
  return entry ? entry[0] : null;
}

function buildCards() {
  const cards = {};
  Object.keys(MAJORS).forEach((id) => {
    const m = MAJORS[id];
    cards[id] = {
      name: m.name,
      keywords: m.keywords,
      uprightMeaning: m.upright,
      reversedMeaning: m.reversed,
      cena: m.cena,
      conselho: m.conselho,
      conselhoInvertido: m.conselhoInvertido,
      astro: null,
      tituloGD: null,
    };
  });
  ['paus', 'copas', 'espadas', 'ouros'].forEach((suitKey) => {
    for (let n = 1; n <= 14; n += 1) {
      const m = MINORS[suitKey][n];
      const entry = DECANS[suitKey]?.[n];
      cards[`${suitKey}-${String(n).padStart(2, '0')}`] = {
        name: `${RANK_NAME[n]} of ${SUIT_NAME[suitKey]}`,
        keywords: m.keywords,
        uprightMeaning: m.upright,
        reversedMeaning: m.reversed,
        cena: m.cena,
        conselho: m.conselho,
        conselhoInvertido: m.conselhoInvertido,
        astro: astroFor(suitKey, n),
        tituloGD: entry ? entry[1] : null,
      };
    }
  });
  return cards;
}

const pack = {
  themeWord: { Amor: 'Love', Carreira: 'Career', Dinheiro: 'Money', Energia: 'Energy', 'Saúde': 'Health' },
  themeOpener: {
    Amor: 'In love',
    Carreira: 'In your career',
    Dinheiro: 'In your finances',
    Energia: 'In your energy',
    'Saúde': 'In health',
  },
  suitTerritory: {
    paus: {
      Amor: 'desire and initiative',
      Carreira: 'drive and projects',
      Dinheiro: 'money that only moves when you move',
      Energia: 'vigor — and how much of it is already spent',
      'Saúde': 'the body in motion, between vigor and exhaustion',
    },
    copas: {
      Amor: 'the bond and what has not yet become words',
      Carreira: 'atmosphere and people',
      Dinheiro: 'decisions driven by emotional worth',
      Energia: 'your emotional state',
      'Saúde': 'the emotional state that carries the rest',
    },
    espadas: {
      Amor: 'the thing that needs to be said',
      Carreira: 'analysis, strategy, and the hard conversation',
      Dinheiro: 'the number seen without the story around it',
      Energia: 'the head, and how much it lets the rest run',
      'Saúde': 'sleep and thought',
    },
    ouros: {
      Amor: 'feeling turned into concrete gesture',
      Carreira: 'craft, deadline, and visible results',
      Dinheiro: 'matter — and here the suit plays at home',
      Energia: 'the physical body and what it can take',
      'Saúde': 'habits and routines that hold over time',
    },
  },
  suitLabel: { paus: 'Wands', copas: 'Cups', espadas: 'Swords', ouros: 'Pentacles' },
  rankRole: {
    1: 'the root of the element, still whole',
    2: 'the degree of polarity, two forces facing each other before anything happens',
    3: 'the degree where the plan leaves the page and shows up in the world',
    4: 'the degree of form that is already starting to weigh',
    5: 'the degree of crisis, where the element loses its balance',
    6: 'the degree of recovery after the crisis',
    7: 'the degree of the trial, passed far from the audience',
    8: 'the degree of movement, when the matter starts moving again',
    9: 'the degree of culmination, with all it carries of solitude',
    10: 'the degree of the limit, completeness already turned excess',
    11: 'the figure still learning the element',
    12: 'the figure that hurls the element outward',
    13: 'the figure that sustains the element from within',
    14: 'the figure that manages the element in the world',
  },
  rankGrades: {
    1: 'Ace — the root of the element: pure potential, still whole and not yet spent.',
    2: 'Two — polarity and choice: two forces facing each other before anything happens.',
    3: 'Three — first manifestation: what was a plan leaves the page and shows up in the world.',
    4: 'Four — stability and consolidation: it has form now, and form is already starting to weigh.',
    5: 'Five — crisis: the element loses its balance. It is the same degree in four elements, which is why it is a fight in Wands, grief in Cups, defeat in Swords, and privation in Pentacles.',
    6: 'Six — recovery: the balance returning after the crisis of the Five.',
    7: 'Seven — trial: the strength is tested from within, far from the audience.',
    8: 'Eight — movement: the energy circulates again and the matter moves.',
    9: 'Nine — culmination: the most the element can hold alone, with all that has of solitude.',
    10: 'Ten — the cycle’s limit: completeness that is already excess and asks for closure.',
    11: 'Page — the one still LEARNING the element: beginnings, curiosity, no mastery yet.',
    12: 'Knight — the one who HURLS the element outward: movement, drive, sometimes excess.',
    13: 'Queen — the one who SUSTAINS the element from within: mastery through lived experience.',
    14: 'King — the one who MANAGES the element in the world: mastery through the exercise of authority.',
  },
  syClassPhrase: {
    'mãe': 'one of the three mothers',
    dupla: 'one of the seven doubles',
    simples: 'one of the twelve simples',
  },
  elements: {
    ar: 'Air', 'água': 'Water', fogo: 'Fire', terra: 'Earth',
    'mercúrio': 'Mercury', lua: 'the Moon', 'vênus': 'Venus', sol: 'the Sun',
    marte: 'Mars', 'júpiter': 'Jupiter', saturno: 'Saturn',
    'áries': 'Aries', touro: 'Taurus', 'gêmeos': 'Gemini', 'câncer': 'Cancer',
    'leão': 'Leo', virgem: 'Virgo', libra: 'Libra', 'escorpião': 'Scorpio',
    'sagitário': 'Sagittarius', 'capricórnio': 'Capricorn', 'aquário': 'Aquarius', peixes: 'Pisces',
  },
  elementLow: { fogo: 'fire', terra: 'earth', ar: 'air', 'água': 'water' },
  frames: {
    abreSemEixo: '{tema}.',
    abre: '{tema} — {eixo}.',
    abreInvertida: '{tema} — {eixo}, inside out.',
    cena: 'On the card, {cena}.',
    eixoNome: 'the axis — {eixo} —',
    eixoNomeSemEixo: 'the axis',
    invertidaPassado: 'Back there, {eixoNome} was already jammed. {significado}',
    invertidaFuturo: '{eixoNome} is still jammed. {significado}. A vector, not a done deal.',
    invertidaPresente: '{eixoNome} is jammed. {significado}',
    invertidaSituacao: 'Situation, reversed {nome}: {eixoNome} is jammed. {significado} In reversed {nome}, {contexto} remain blocked.',
    invertidaTensao: 'Tension in reversed {nome}: {eixoNome} is jammed. {significado}',
    invertidaProximoPasso: 'Next step, reversed {nome}: {eixoNome} remains jammed. {significado}. A vector, not a done deal.',
    diretaPassado: 'Root already played out: {significado}. It is ground now, not news.',
    diretaFuturo: 'If the steering stays the same: {significado}. A vector, not a done deal.',
    diretaPresente: '{significado}',
    diretaSituacao: 'Situation, {nome}: {significado}. In {nome}, {contexto} define the frame.',
    diretaTensao: 'Tension in {nome}: {significado}. Shadow: {sombra}.',
    diretaProximoPasso: 'Next step, {nome}: {significado}. A vector, not a done deal.',
    diretaSemCasa: '{significado}',
    atributoFallback: 'the symbol itself',
    maiorPassado: '{opener}: {nome}, arcanum {numero}, the letter {letra} in the Golden Dawn scheme.',
    maiorFuturo: '{opener}: {nome}, path {caminho} on the Tree of Life, under {atributo} in the Golden Dawn scheme.',
    maiorPresente: '{opener}: {nome}, arcanum {numero}, under {atributo} in the Golden Dawn scheme.',
    maiorSituacao: '{opener}: {nome}; arcanum {numero}, letter {letra}; Golden Dawn.',
    maiorTensao: '{opener}: {nome}; letter {letra}, under {atributo}; Golden Dawn.',
    maiorProximoPasso: '{opener}: {nome}; arcanum {numero}, Tree of Life, path {caminho}; Golden Dawn.',
    campo: '{opener}, {naipe} covers {territorio}.',
    campoSemTerritorio: '{opener}, {naipe} speaks.',
    asPassado: '{campo} The Ace is the {astro}, and at that point the potential was still whole — by the Golden Dawn scheme.',
    asFuturo: '{campo} The Ace is the {astro} — seed, not harvest (Golden Dawn scheme).',
    asPresente: '{campo} The Ace is the {astro}, potential not yet spent — by the Golden Dawn scheme.',
    asSituacao: '{campo} {nome}: {astro}; situated potential; Golden Dawn.',
    asTensao: '{campo} {nome}: {astro}; potential under friction; Golden Dawn.',
    asProximoPasso: '{campo} {nome}: {astro}; seed in action; Golden Dawn.',
    cortePassado: '{campo} Golden Dawn: {astro}, {papel}.',
    corteFuturo: '{campo} Golden Dawn: {astro} — the one steering from here.',
    cortePresente: '{campo} Golden Dawn: {astro} — {papel}.',
    corteSituacao: '{campo} {nome}: {astro}; {papel}; Golden Dawn.',
    corteTensao: '{campo} {nome}: friction in {astro}; {papel}; Golden Dawn.',
    corteProximoPasso: '{campo} {nome}: movement in {astro}; {papel}; Golden Dawn.',
    numeradaPassado: '{campo} Golden Dawn: {astro}, {papel}.',
    numeradaFuturo: '{campo} Golden Dawn: {tituloGD}, {astro} — the one steering from here.',
    numeradaPresente: '{campo} Golden Dawn: {tituloGD}, {astro} — {papel}.',
    numeradaSituacao: '{campo} {nome}: {tituloGD}; {astro}; {papel}; Golden Dawn.',
    numeradaTensao: '{campo} {nome}: {tituloGD} under friction; {astro}; {papel}; Golden Dawn.',
    numeradaProximoPasso: '{campo} {nome}: {tituloGD} directs; {astro}; {papel}; Golden Dawn.',
    menorFallback: '{campo} That is where this card speaks from, in the Golden Dawn scheme.',
    conselhoFuturo: 'What shifts the vector: {conselho}',
    conselhoPresente: '{conselho}',
    conselhoTensao: '{nome}, care: {conselho}',
    conselhoProximoPasso: '{nome}, move: {conselho}',
  },
  waite: {
    titulo: 'What A. E. Waite wrote in 1911 — the card {orientacao} in his list',
    orientacao: { direta: 'upright', invertida: 'reversed' },
    notas: {
      'major-00': 'In the 1911 list the Fool is exactly this — folly, not a leap of faith. The app reads Pamela Colman Smith’s IMAGE (the foot at the cliff’s edge), which is the mainstream contemporary school. It is a choice, and it is not Waite’s.',
      'major-03': 'Notice: in Waite the REVERSED Empress is light and truth, and his upright includes "difficulty, doubt, ignorance". The idea that reversed always means the energy jammed is a 20th-century one (Gray, Pollack, Greer), not 1911.',
      'major-04': 'Another reversal that in Waite reads better than the upright. The app uses the contemporary school (block, excess, interiorization) and says it is contemporary.',
      'major-09': 'Note the ellipsis: this is an EXCERPT from the Hermit’s upright list, not the whole of it — the source records that Waite’s upright meaning "includes" these four words, alongside others. The app stays with the image, the lantern lighting one step at a time, and what it will not do is pretend the 1911 list is all kindness and wisdom.',
      'major-10': 'The reversed Wheel is POSITIVE in Waite. It is the cleanest example that "reversed = opposite" was never his rule.',
      'major-13': '"Death never meant death" is false as a historical claim: the 1911 list opens exactly like this. Reading the card as the end of a form, as transformation, is a 20th-century ethical choice — it is the one this app makes, and we will not pretend it is old.',
      'major-14': 'A reversal that in Waite is neither better nor worse — it is LATERAL, about another subject entirely. Once again: his reversal is not an opposite.',
      'major-16': 'Eight nouns and a full stop. This is the dry register of the tradition, and it is why the app does not sweeten the Tower. What the app does NOT do is turn it into a verdict: the card describes the nature of what is at stake; it does not decree the outcome.',
      'major-17': 'The most striking case in the list: hope is Waite’s SECOND reading, presented as "another version". The app keeps the hope, which is the modern reading and the right one for the product, and never credits it to the Pictorial Key.',
      'copas-05': 'The model for stating a hard card without lying: it names the whole loss, and what remains afterward is a FACT OF THE IMAGE (two cups still standing), not a stock consolation.',
      'espadas-03': 'It is the END of his entry — hence the ellipsis — and Waite closes the Three of Swords by refusing to explain, because the image has already spoken. It is the oldest license this app has for being direct instead of padding. And it is no coincidence that it is this card: the Three of Swords is where Pamela Colman Smith’s debt to the Sola Busca — an Italian deck of c. 1491 — is most documented.',
    },
  },
  dignidade: {
    intro: 'At this table of three, the middle card is not read alone: the two neighbors strengthen or weaken it, according to each one’s element — fire, water, air, or earth. Here the middle is {nome}, of {elemento}, flanked by {vizinhas}. {veredito} And this is not me improvising: it is elemental dignity, the triad rule of the "Book T" (S. L. MacGregor Mathers, late 19th century, published by Regardie in 1937-1940).',
    vizinha: '{nome} ({elemento})',
    vizinhaForaDaRegra: '{nome} (a planet card — it stays outside this rule)',
    vizinhasConector: ' and ',
    vereditos: {
      duasContrarias: '{nome} comes out ill-dignified: both sides are contrary to its element, and the tradition says it loses force there — the matter in the middle finds no support in either neighboring house.',
      dividida: '{nome} is split: one side sustains its element and the other is contrary, so its force depends on which of the two houses you look at.',
      umaContraria: '{nome} comes out weakened on one side, with nothing on the other to make up for it.',
      duasIguais: '{nome} comes out strongly reinforced: all three share one element, and the rule cuts both ways — it reinforces what the card has of good and what it has of hard.',
      fortalecida: '{nome} comes out strengthened: both neighbors are of the same or a friendly element, and the tradition reads that as energy running unobstructed.',
      apoioDeUmLado: '{nome} gets support from one side only; the other is passive, neither helping nor hindering.',
      passiva: '{nome} stands on passive ground: neither neighbor reinforces nor opposes its element.',
    },
  },
  spread: {
    grauRepetido: 'The same degree — the card’s number — came up {qtd} times in this spread. Reading the set weighs that pattern more than any single card — a practice that took hold in the 20th century. {grade}',
    maiores: '{qtd} Major Arcana out of {total} cards: the contemporary reading takes this as a matter not entirely in your hands — backdrop, not the detail of the day.',
    naipeDominante: 'A spread dominated by {naipe}: the whole matter is concentrated in that territory.',
    naipeDominanteLabel: {
      paus: 'Wands (fire — action and desire)',
      copas: 'Cups (water — feeling and bonds)',
      espadas: 'Swords (air — mind and truth)',
      ouros: 'Pentacles (earth — matter and body)',
    },
  },
  tradicaoNota: {
    astroComTitulo: '{tituloGD} ({astro})',
    letraComClasse: 'Hebrew letter {letra}, {classe} of the Sepher Yetzirah — the "Book of Formation", an old text of Jewish mysticism',
    letraSemClasse: 'Hebrew letter {letra}',
    caminho: 'path {caminho} on the Tree of Life, the map of the Kabbalah',
    separador: ' · ',
  },
  cards: buildCards(),
};

export default pack;
