export const PACK = {
  title: 'Seu Álbum Cósmico',
  subtitle: '78 cartas, encontros reais e padrões que só o tempo revela.',
  tabs: { album: 'Álbum', mirror: 'Espelho' },
  progress: ({ seen, total }) => `${seen} de ${total} reveladas`,
  progressComplete: 'O baralho inteiro já passou pelas suas mãos.',
  progressMissing: ({ count }) =>
    count === 1 ? 'Só 1 carta ainda guarda o mistério.' : `${count} cartas ainda guardam o mistério.`,
  draw: 'Fazer uma tiragem',
  searchPlaceholder: 'Buscar carta pelo nome',
  filters: {
    all: 'Todas',
    seen: 'Reveladas',
    unseen: 'Ocultas',
    favorites: 'Favoritas',
    repeated: 'Recorrentes',
  },
  groups: { maiores: 'Arcanos Maiores', paus: 'Paus', copas: 'Copas', espadas: 'Espadas', ouros: 'Ouros' },
  noResultsTitle: 'Nenhuma carta aqui',
  noResultsBody: 'Tente outro nome ou filtro. Suas cartas reveladas continuam guardadas.',
  hiddenGroupCount: ({ count }) => count === 1 ? '1 carta oculta neste grupo' : `${count} cartas ocultas neste grupo`,
  hiddenGroupHint: 'As posições não são exibidas para não revelar qual carta falta. Faça uma tiragem para descobrir.',
  favorite: 'Favoritar carta',
  unfavorite: 'Remover dos favoritos',
  encountersTitle: 'Seus encontros',
  encountersCount: ({ count }) =>
    count === 1 ? 'Apareceu 1 vez nas suas tiragens' : `Apareceu ${count} vezes nas suas tiragens`,
  encountersOrientation: ({ upright, reversed }) => `${upright} direta · ${reversed} invertida`,
  firstSeen: ({ date }) => `Primeiro encontro registrado em ${date}`,
  lastSeen: ({ date }) => `Encontro mais recente em ${date}`,
  legacyHistory: 'Esta carta já estava no seu álbum. O histórico detalhado começa no próximo encontro.',
  legacyBaseline: 'Esta carta já estava no álbum antes desta medição. As datas e orientações acima começam no primeiro encontro registrado agora.',
  studyTitle: 'Estude esta carta',
  studySubtitle: 'Compare as duas orientações sem alterar nenhuma tiragem.',
  upright: 'Direta',
  reversed: 'Invertida',
  keywords: 'Palavras-chave',
  scene: 'O que observar na imagem',
  meaning: 'Leitura da orientação',
  advice: 'Pergunta para refletir',
};
