// Brief theme lenses for the 22 Major Arcana.
// They share the PT pack's editorial boundary: situated reflection without
// prediction, diagnosis, or newly invented claims about tradition.

const pack = {
  'major-00': {
    Amor: 'The foot at the edge asks whether this approach comes from openness or impulse. Before the leap, pair freedom with one clear boundary.',
    Carreira: 'The light bundle favors testing a path whose outcome remains unknown. Start small and study the ground before leaving familiar work behind.',
    Dinheiro: 'The cliff turns spontaneity into a money caution: curiosity fits; a bet with no margin does not. Set a risk that leaves essentials intact.',
    Energia: 'The traveler is ready to begin, while the dog tugs at his clothes. Choose an enlivening adventure without ignoring the cue for caution.',
    Saúde: 'Through a self-care lens, this step asks for presence and a safe setting. Prefer one simple routine change over a leap beyond your limits.',
  },
  'major-01': {
    Amor: 'The Magician puts intention and resources on one table. Instead of winning someone with a promise, show through one action what bond you want to build.',
    Carreira: 'All four tools are available; the professional challenge is choosing one and using it with focus rather than displaying scattered potential.',
    Dinheiro: 'Skill becomes a resource through execution. Take stock of what you can produce and test a concrete use before counting on income.',
    Energia: 'One hand points toward purpose, the other toward the ground. Put your drive into one task that joins idea and gesture instead of activating everything.',
    Saúde: 'In self-care, having many resources does not replace consistency. Choose an accessible practice, notice your response, and adjust without promising the body an outcome.',
  },
  'major-02': {
    Amor: 'Between two pillars, the High Priestess protects what remains unsaid. Notice the silences and ask for context before filling gaps with assumptions.',
    Carreira: 'The half-hidden scroll suggests incomplete information. Gather the missing fact and keep your inner reading private before announcing a professional decision.',
    Dinheiro: 'Not every term is visible in this negotiation. Read the details, wait for pending information, and separate intuition from an advantage not yet verified.',
    Energia: 'The seated guardian wastes no motion. A quiet interval can show which demand deserves attention and which one merely creates noise.',
    Saúde: 'This card supports careful listening, not self-diagnosis. Record what you notice and take concrete concerns to a qualified health professional.',
  },
  'major-03': {
    Amor: 'In the wheat field, affection grows through sustained presence. Notice whether care moves both ways or one person has become the bond’s only source.',
    Carreira: 'The Empress points to work that needs cultivation, not haste. Protect time to create and define what a mature delivery looks like.',
    Dinheiro: 'Abundance begins by making existing resources productive. Nurture one useful asset and avoid mistaking generosity for carrying every expense alone.',
    Energia: 'The fertile field asks for movement between producing and receiving. Reclaim some energy for your own work before every demand dries out creativity.',
    Saúde: 'For everyday wellbeing, the image invites basic support and kindness toward yourself. Choose feasible care without making productivity a measure of the body.',
  },
  'major-04': {
    Amor: 'The stone throne asks which boundaries make the bond safer and which became commands. Name one rule that protects both people without controlling either.',
    Carreira: 'The Emperor favors visible responsibility: scope, deadline, and authority need definition. Give the work structure before asking it to hold.',
    Dinheiro: 'Dry mountain and stone call for a foundation, not the appearance of control. Organize fixed obligations and decision room before taking on a new commitment.',
    Energia: 'Structure can conserve effort by reducing repeated decisions. Give the day a simple frame with enough space to keep it from becoming rigid.',
    Saúde: 'Useful self-care discipline fits real life. Build stable, revisable support without punishing the body when the routine needs to change.',
  },
  'major-05': {
    Amor: 'Before the teacher and two students, examine which relationship rules were inherited. Keep only those that still represent the pair’s values.',
    Carreira: 'The keys at the Hierophant’s feet point toward access through learning. Seek experienced guidance, then understand the method before adopting it as law.',
    Dinheiro: 'Specialist advice can clarify a choice when expertise and interests are transparent. Do not hand over the decision along with the doubt.',
    Energia: 'A familiar ritual can reduce distraction. Reuse a practice that once shaped the day without obeying out of habit what has lost meaning.',
    Saúde: 'This lens values responsible guidance and an understandable routine. For clinical concerns, use qualified care; symbolic tradition does not replace health assessment.',
  },
  'major-06': {
    Amor: 'Under the angel, the Lovers hold the instant before a choice. The central question is whether desire, agreement, and values point toward the same bond.',
    Carreira: 'Two possibilities require more than comparing benefits. Choose the route that sustains your professional values while accepting what stays behind.',
    Dinheiro: 'This money decision exposes competing priorities. Before choosing, state the value each option protects and the cost neither option removes.',
    Energia: 'Drive split between two directions loses force in the middle. Name the conflict in values and give full presence to one choice at a time.',
    Saúde: 'For wellbeing, alignment matters more than a perfect rule. Select care compatible with your limits, available support, and appropriate guidance.',
  },
  'major-07': {
    Amor: 'The sphinxes pull opposite ways while the driver holds direction. Talk about a shared course before accelerating the relationship.',
    Carreira: 'The Chariot gathers rival forces around one target. Define a measurable professional destination and coordinate each front without confusing speed with progress.',
    Dinheiro: 'Undirected momentum can create activity without progress. Give each meaningful expense a purpose and review the ones pulling against your priority.',
    Energia: 'Power is available, but it needs a course. Pick one destination for today and steer inner tensions without trying to crush them.',
    Saúde: 'In self-care, intensity does not equal suitability. Match pace to your signals and circumstances, especially when two demands compete.',
  },
  'major-08': {
    Amor: 'The woman meets the lion without violence. A firm, gentle conversation can reveal whether the relationship receives boundaries or responds only to pressure.',
    Carreira: 'Strength favors influence without brute confrontation. Hold your position through preparation and patience, especially when the response turns defensive.',
    Dinheiro: 'Mastery here is not squeezing until something breaks; it is containing an urge without denying it. Place a pause between wanting and buying.',
    Energia: 'The image asks you to regulate power rather than erase it. Direct intensity into one precise action and leave brute force off the schedule.',
    Saúde: 'Gentleness and firmness can share a care routine. Respect discomfort and individual progression without using extreme effort as proof of worth.',
  },
  'major-09': {
    Amor: 'The lantern lights only the next step. Time apart can clarify the bond as long as retreat does not become disappearance without conversation.',
    Carreira: 'The Hermit trades exposure for investigation. Make room to deepen one skill and return with a sharper question, not distance alone.',
    Dinheiro: 'Before following somebody else’s movement, examine your own numbers. The lantern calls for a private review focused on the next commitment.',
    Energia: 'Reducing noise can give the day direction again. Choose a deliberate interval and a return point so retreat does not become isolation.',
    Saúde: 'Inner listening can support self-care without becoming solitary. If something concerns you, organize what you noticed and ask a specific person for help.',
  },
  'major-10': {
    Amor: 'The wheel invites you to name the bond’s cycle: closeness, distance, repair, or repetition. Look for where your response can still change the turn.',
    Carreira: 'A changing context shifts your place on the wheel. Separate what you cannot control from the skill you can prepare for another opening.',
    Dinheiro: 'Fluctuation calls for margin and pattern awareness, not a wager on luck. Study inflow and outflow before reacting to the current turn.',
    Energia: 'Not every day occupies the same point on the wheel. Match expectation to the moment and keep one small action through the variation.',
    Saúde: 'Routines move through cycles too. Record changes, adapt care prudently, and seek professional assessment for a persistent or concerning sign.',
  },
  'major-11': {
    Amor: 'Sword and scales ask for measured truth. Separate facts, interpretation, and each person’s responsibility before seeking a verdict on the relationship.',
    Carreira: 'Justice favors explicit criteria. Document deliveries, agreements, and consequences so a professional decision does not rest on impression alone.',
    Dinheiro: 'Put amounts, deadlines, and obligations on the actual scales. Sign only after understanding the exchange and your share of the account.',
    Energia: 'Imbalance becomes easier to read when the day is viewed without judgment. Compare demand with capacity and remove one obligation that does not fit.',
    Saúde: 'Through a wellbeing lens, evidence matters more than blame. Observe facts and context; clinical questions belong in qualified assessment, not in a card.',
  },
  'major-12': {
    Amor: 'The Hanged Man changes the view by suspending movement. Stop forcing an answer and look at the bond from the place you usually ignore.',
    Carreira: 'Pushing from the same angle tightens the professional knot. Use the pause to review your premise, the cost of waiting, and the required delivery.',
    Dinheiro: 'A suspended choice still carries a cost. Before releasing it, change perspective and identify the sacrifice built into each option.',
    Energia: 'Stopping can be legitimate work today. Release one insistence and notice the perspective that appears when urgency no longer directs the scene.',
    Saúde: 'A pause does not have to mean abandoning care. Adapt the demand to what is safe now and seek guidance if a limitation persists.',
  },
  'major-13': {
    Amor: 'Death describes a form of relationship that ended, not literal death. Acknowledge the closure before trying to rename it as continuity.',
    Carreira: 'The sun between the towers appears beyond the passage. Close an exhausted role, method, or cycle to free attention for what can be rebuilt.',
    Dinheiro: 'An old commitment may no longer serve its purpose. Close it clearly, calculate consequences, and avoid funding something only because it already began.',
    Energia: 'Holding a finished cycle consumes the strength needed for transition. Choose one concrete act of closure and protect room for a different rhythm.',
    Saúde: 'Transformation here is a routine metaphor, never a prognosis. Leave an unworkable habit with suitable support and replace it with feasible care.',
  },
  'major-14': {
    Amor: 'Liquid moves gradually between two cups. Small, reciprocal adjustments can reveal the measure of this meeting better than one grand declaration.',
    Carreira: 'Temperance combines resources without erasing differences. Integrate two skills in stages and assess the mixture before expanding the project.',
    Dinheiro: 'The card favors proportion: what comes in, what leaves, and what remains available. Correct one specific excess instead of redesigning everything.',
    Energia: 'One foot in water and one on land call for gradual transition. Alternate effort with recovery and notice which dose keeps the day livable.',
    Saúde: 'Moderation guides a routine here, not a prescription. Make gradual changes within your limits and take specific needs to an appropriate professional.',
  },
  'major-15': {
    Amor: 'The chains are loose enough to leave, yet they also offer something in return. Name the hidden gain that keeps this relationship pattern in place.',
    Carreira: 'The Devil exposes an agreement that binds through immediate reward. Examine which benefit feeds dependence and which boundary could restore choice.',
    Dinheiro: 'Desire, debt, or status may have become a chain. Make the benefit feeding the habit visible before negotiating a realistic exit.',
    Energia: 'A recurring urge takes more space while it remains unnamed. Notice trigger, reward, and cost, then choose one chain you can begin to loosen.',
    Saúde: 'The card may reflect attachment to a routine, not diagnosis or blame. Seek suitable support for patterns that feel difficult to change alone.',
  },
  'major-16': {
    Amor: 'Lightning does not create the crack; it reveals it. State which part of the bond no longer supports truth, safety, or respect.',
    Carreira: 'The crown falls from an already fragile tower. Protect people and essential work, then rebuild the process from whatever held through impact.',
    Dinheiro: 'An unstable financial base calls for containment before expansion. Find the fissure, reduce exposure, and avoid rebuilding the same structure under another name.',
    Energia: 'After impact, firm ground becomes the priority. Suspend what is not essential and place your presence in one recoverable front.',
    Saúde: 'The Tower does not predict an emergency. For an acute sign or concrete concern, seek care; symbolically, review a routine that lost support.',
  },
  'major-17': {
    Amor: 'Under eight stars, water is offered to pool and earth. Reconnection asks for reciprocal vulnerability, not faith used to overlook absence.',
    Carreira: 'The Star comes after rupture and works at a patient scale. Return to an ambition through evidence that is small, visible, and consistent.',
    Dinheiro: 'Financial hope gains ground when it becomes repeatable action. Direct a modest resource toward what still works and track it without imagining returns.',
    Energia: 'The two jugs show replenishment distributed across places. Choose a concrete source of inspiration and also support the routine that makes it sustainable.',
    Saúde: 'In this self-care reading, water suggests continuity and basic attention. Value small, real supports without assigning a clinical effect to the symbol.',
  },
  'major-18': {
    Amor: 'Between dog and wolf, a path exists while moonlight distorts its edges. Avoid choosing from anxiety; ask for clarity about what remains ambiguous.',
    Carreira: 'The Moon points to an incomplete scene, rumor, or projected fear. Separate confirmed information from what imagination supplied before changing direction.',
    Dinheiro: 'Hazy figures do not become safe through intuition. Delay the commitment, verify terms, and ask another person to inspect what looks too good.',
    Energia: 'The night path asks for a smaller step and less stimulation. Name one verifiable fear and leave the rest unresolved until more becomes visible.',
    Saúde: 'Sensations deserve attention, but the card does not explain them. Record context and consult about symptoms without turning fear into diagnosis.',
  },
  'major-19': {
    Amor: 'The child beneath the sun invites visible, uncomplicated affection. Say what you appreciate and notice whether joy can exist without performance.',
    Carreira: 'Sunflowers facing the light favor clear recognition. Show one concrete delivery and let its value be understood without unnecessary ornament.',
    Dinheiro: 'Clarity may matter more than a shining opportunity. Simplify the figures, expose costs, and choose what still looks sound when seen whole.',
    Energia: 'The Sun magnifies what is present. Use your readiness in one simple, shareable activity without turning enthusiasm into an impossible schedule.',
    Saúde: 'Wellbeing does not need to become a performance. Notice what supports sustainable vitality and respect signals that call for adjustment or assessment.',
  },
  'major-20': {
    Amor: 'The trumpet calls for a response to what remains pending. Revisit an emotional decision through what you learned without reducing anyone to an old mistake.',
    Carreira: 'Judgement separates assessment from condemnation. Review your path, recognize evidence of change, and answer the work that still feels meaningful.',
    Dinheiro: 'A past choice returns for accountability. Correct what you can with current numbers without letting shame replace planning.',
    Energia: 'A call takes shape when it receives a response. Pick one pending matter worth answering and use self-criticism as information, not identity.',
    Saúde: 'Reviewing habits can be useful without moral judgment. Consider professional support for health decisions and assess behaviors rather than personal worth.',
  },
  'major-21': {
    Amor: 'Inside the laurel wreath, the cycle asks for full recognition. Celebrate what the bond completed and name what needs closure before another beginning.',
    Carreira: 'The World gathers once-scattered parts into a finished delivery. Complete the remaining detail and record what you learned before opening another front.',
    Dinheiro: 'Financial completion includes review, settlement, and room for transition. Close the entire account before treating the next goal as available.',
    Energia: 'The dance inside the wreath shows movement with a boundary. Finish one open task and let completion return mental space.',
    Saúde: 'Integration here means viewing routine and support as a whole. Recognize feasible progress and review what remains without demanding bodily perfection.',
  },
};

export default pack;
