export default {
  listen: 'Escuchar',
  preparing: 'Preparando la voz…',
  cancel: 'Cancelar',
  stop: 'Detener',
  retry: 'Intentar de nuevo',
  privacyLabel: 'Cómo trata tus datos la voz',
  hint: 'Genera y reproduce esta lectura con una voz neuronal.',
  errors: {
    login_required: 'Inicia sesión para escuchar esta lectura.',
    email_unverified: 'Confirma tu correo para usar la voz.',
    voice_quota_exhausted: 'Tu límite de voz de hoy terminó. Inténtalo de nuevo mañana.',
    voice_global_quota_exhausted: 'La capacidad de voz de Cosmic Guide terminó por hoy. Inténtalo de nuevo mañana.',
    voice_text_too_long: 'Esta lectura es demasiado larga para generar audio.',
    voice_rate_limited: 'Hay demasiadas solicitudes de voz. Espera unos minutos.',
    voice_timeout: 'La voz tardó más de lo esperado. Inténtalo de nuevo.',
    voice_unavailable: 'La voz neuronal no está disponible ahora.',
    network_error: 'No hay conexión para preparar la voz. Revisa tu internet.',
    cancelled: '',
    default: 'No pudimos preparar la voz. Inténtalo de nuevo.',
  },
  privacy: {
    data: 'Al tocar Escuchar, el texto de esta lectura pasa por nuestro servidor y por ElevenLabs para generar una voz sintética.',
    process: 'La voz requiere una cuenta confirmada. Guardamos el conteo diario y una caché temporal del audio por hash durante un máximo de 24 horas; ElevenLabs trata el texto según su propia política.',
  },
};
