export default {
  listen: 'Ouvir',
  preparing: 'Preparando a voz…',
  cancel: 'Cancelar',
  stop: 'Parar',
  retry: 'Tentar novamente',
  privacyLabel: 'Como a voz trata seus dados',
  hint: 'Gera e reproduz esta leitura com uma voz neural.',
  errors: {
    login_required: 'Entre na sua conta para ouvir esta leitura.',
    email_unverified: 'Confirme seu e-mail para usar a voz.',
    voice_quota_exhausted: 'Seu limite de voz de hoje terminou. Tente novamente amanhã.',
    voice_global_quota_exhausted: 'A capacidade de voz do Cosmic Guide terminou por hoje. Tente novamente amanhã.',
    voice_text_too_long: 'Esta leitura é longa demais para gerar em áudio.',
    voice_rate_limited: 'Muitos pedidos de voz agora. Aguarde alguns minutos.',
    voice_timeout: 'A voz demorou além do esperado. Tente novamente.',
    voice_unavailable: 'A voz neural está indisponível agora.',
    network_error: 'Sem conexão para preparar a voz. Verifique sua internet.',
    cancelled: '',
    default: 'Não foi possível preparar a voz. Tente novamente.',
  },
  privacy: {
    data: 'Ao tocar em Ouvir, o texto desta leitura passa pelo nosso servidor e pela ElevenLabs para gerar uma voz sintética.',
    process: 'A voz exige uma conta confirmada. Guardamos a contagem diária e um cache temporário do áudio por hash por até 24 horas; a ElevenLabs trata o texto segundo a política dela.',
  },
};
