export default {
  listen: 'Listen',
  preparing: 'Preparing voice…',
  cancel: 'Cancel',
  stop: 'Stop',
  retry: 'Try again',
  privacyLabel: 'How voice handles your data',
  hint: 'Generates and plays this reading with a neural voice.',
  errors: {
    login_required: 'Sign in to listen to this reading.',
    email_unverified: 'Confirm your email to use voice.',
    voice_quota_exhausted: 'You have reached today’s voice limit. Try again tomorrow.',
    voice_global_quota_exhausted: 'Cosmic Guide’s voice capacity has been reached for today. Try again tomorrow.',
    voice_text_too_long: 'This reading is too long to generate as audio.',
    voice_rate_limited: 'There are too many voice requests right now. Wait a few minutes.',
    voice_timeout: 'Voice generation took longer than expected. Try again.',
    voice_unavailable: 'Neural voice is unavailable right now.',
    network_error: 'There is no connection to prepare voice. Check your internet.',
    cancelled: '',
    default: 'We could not prepare the voice. Try again.',
  },
  privacy: {
    data: 'When you tap Listen, this reading’s text passes through our server and ElevenLabs to generate a synthetic voice.',
    process: 'Voice requires a confirmed account. We keep a daily count and a temporary hash-keyed audio cache for up to 24 hours; ElevenLabs handles the text under its own policy.',
  },
};
